### PR TITLE
fix(BaseClient): Remove selfbot ability

### PR DESCRIPTION
**Pull request by xHyroM**
**Please describe the changes this PR makes and why it should be merged:**

Removing this will prevent people from raiding easier. Yes they can do fork, but I don't think a well known library like this should support it.

How can you make a self bot?
`new Client({_tokenType:""})`

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Comment by xHyroM** [comment]
Alternatively, I can make it so that there will be support for `bot` type and `bearer` but I don't think it's necessary to do that and just do it this way.

**Review by SpaceEEC — APPROVED** [review]
This is a, now not needed anymore, remnant of #1883, which I think was RPC related.

**Review by kyranet — APPROVED** [review]

**Comment by vaporox** [comment]
So why not remove that parameter now that it's hard coded?

**Comment by xHyroM** [comment]
> 
> 
> So why not remove that parameter now that it's hard coded?

Good point. I've already deleted it.

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
