### PR TITLE
fix(Message): Message#createdTimestamp uses deconstructed message id to get timestamp

### PR DESCRIPTION
**Pull request by zaida04**
https://i.imgur.com/6RlLWOW.png

First PR yeet

**Status**

- [X] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by didinele** [comment]
But... why? Discord already gives us data about when it was created.

**Comment by NotSugden** [comment]
@didinele partial message data might only have the ID, and so the date would be invalid for partial objects

**Comment by didinele** [comment]
Oh, I guess that's fair enough. Should've probably mentioned in the PR body.

**Comment by advaith1** [comment]
it's not marked as optional or nullable in Discord docs, so discord.js should always have it

**Comment by NotSugden** [comment]
partial objects aren't always constructed with the full data from discord, eg in the messageReactionAdd action the `message_id` is only recieved from discord, and a partial Message is constructed with that

https://github.com/discordjs/discord.js/blob/master/src/client/actions/Action.js#L52-L57
https://github.com/discordjs/discord.js/blob/master/src/client/actions/Action.js#L27-L29

**Comment by Assfugil** [comment]
Another example is the MESSAGE_DELETE event where only the guild id,channel id and message id is available.

**Comment by advaith1** [comment]
Have the (Discord) devs ever said why message.timestamp exists in the first place?

**Pull request merged**
