### PR TITLE
refactor(MessagePayload): rename APIMessage

### PR DESCRIPTION
**Pull request by monbrey**
A much simpler version of my previous PR that doesn't have scope creep.

This refactors APIMessage to MessagePayload, a naming convention that doesn't clash with typings, better fits its purpose and aligns with future development plans in this space.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Review by SpaceEEC — DISMISSED** [review]
Can you also update the identifiers to use `messagePayload` or something the like?

https://github.com/discordjs/discord.js/blob/5af2ef5fbc7ad11281f38384c360ae79efe63b39/src/structures/interfaces/TextBasedChannel.js#L172
https://github.com/discordjs/discord.js/blob/5af2ef5fbc7ad11281f38384c360ae79efe63b39/src/structures/interfaces/InteractionResponses.js#L75
https://github.com/discordjs/discord.js/blob/5af2ef5fbc7ad11281f38384c360ae79efe63b39/src/structures/Webhook.js#L161
https://github.com/discordjs/discord.js/blob/5af2ef5fbc7ad11281f38384c360ae79efe63b39/src/structures/APIMessage.js#L244

**Review by iCrawl — APPROVED** [review]

**Comment by ImRodry** [comment]
Can you also rename APIMessageRaw to APIMessage to be consistent with the other Discord API docs links? I only added raw so it wouldn't conflict with this class
https://github.com/discordjs/discord.js/blob/5af2ef5fbc7ad11281f38384c360ae79efe63b39/src/structures/APIMessage.js#L324-L327
(as well as every other instance where this appears)

**Comment by iCrawl** [comment]
This needs a rebase.

**Comment by vaporox** [comment]
You also need to remove the `as Raw...` aliases from the `discord-api-types` imports, otherwise you can't use the actual names

**Comment by monbrey** [comment]
I must have reintroduced them in the rebase. Will remove again.

**Review by SpaceEEC — APPROVED** [review]

**Comment by iCrawl** [comment]
This needs a rebase.

**Review by kyranet — APPROVED** [review]

**Pull request merged**
