### PR TITLE
docs(erlpack): discordapp to discord

### PR DESCRIPTION
**Pull request by Papaia**
**Please describe the changes this PR makes and why it should be merged:**
Seems like the Discord github organization moved from @discordapp to @discord, so this PR updates references of `discordapp/erlpack` to `discord/erlpack`.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by advaith1** [comment]
The peer-dep always warns anyway because it compares the string to the version number of the installed package, but #4272 removes all of the peer deps

**Comment by Monbrey** [comment]
It removes them as peer deps from the package.json to prevent npm7 from installing them automatically.

They should still be in the documentation as optional addons, and docs should still be updated.

**Comment by ItsPapaia** [comment]
#4272 is not yet merged, when will be, I'd update the conflict here.

**Comment by iCrawl** [comment]
You could actually just remove the change you made, and whenever either gets merged there will be no conflict.

**Pull request merged**
