### PR TITLE
types(LinkButtonOptions): Add typings for urls in link buttons

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

Discord only allows the following URL schemes for link buttons:
- `https`
- `http`
- `discord`

This enforces URLs in link buttons to use one of the schemes listed above.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by monbrey** [comment]
Is this a validation we want to apply in our library? We normally avoid imposing these restrictions in case Discord changes them at some point.

**Comment by suneettipirneni** [comment]
Yeah this might be too premature, but up to you all.

**Comment by iCrawl** [comment]
Yeah I think this case would be ok 👍

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Comment by iCrawl** [comment]
This needs a rebase.

**Pull request closed without merging**
