### PR TITLE
refactor: Use `GuildFeature` enum

### PR DESCRIPTION
**Pull request by Jiralite**
**Please describe the changes this PR makes and why it should be merged:**
Some strings can be replaced with `GuildFeature`.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by DraftProducts — APPROVED** [review]

**Comment by JosPoka** [comment]
@SpaceEEC @iCrawl Please review

**Review by SpaceEEC — APPROVED** [review]

**Review by vvito7 — COMMENTED** [review]
Could you also use the enum in these?
https://github.com/discordjs/discord.js/blob/4df491ce8578a1b01ee8412a4df8137a302e7202/packages/discord.js/src/structures/Guild.js#L513
https://github.com/discordjs/discord.js/blob/4df491ce8578a1b01ee8412a4df8137a302e7202/packages/discord.js/src/structures/Guild.js#L606

**Comment by almeidx** [comment]
> Could you also use the enum in these?
> 
> https://github.com/discordjs/discord.js/blob/4df491ce8578a1b01ee8412a4df8137a302e7202/packages/discord.js/src/structures/Guild.js#L513
> 
> 
> https://github.com/discordjs/discord.js/blob/4df491ce8578a1b01ee8412a4df8137a302e7202/packages/discord.js/src/structures/Guild.js#L606

Already done

**Comment by vvito7** [comment]
... I didn't saw it, sorry

**Pull request merged**
