### PR TITLE
Stickers added

### PR DESCRIPTION
**Pull request by Raksix**
client.on('message', msg => msg.stickers)

**Please describe the changes this PR makes and why it should be merged:**

client.on('message', msg => msg.stickers) 

**Status and versioning classification:**

### CODE REVIEW

**Comment by Raksix** [comment]
if('stickers' in data){
      this.stickers = data.stickers
    } else if (!this.stickers) {
      this.stickers = null;
    }

**Comment by iShibi** [comment]
#4909

**Comment by Raksix** [comment]
> #4909

But I can't get this message sticker data for Sticker ban system

**Comment by kyranet** [comment]
> > #4909
> 
> But I can't get this message sticker data for Sticker ban system

You can, the property being missing from Message's type is just an oversight.

Closing as duplicate.

**Comment by Raksix** [comment]
> > > #4909
> > 
> > 
> > But I can't get this message sticker data for Sticker ban system
> 
> You can, the property being missing from Message's type is just an oversight.
> 
> Closing as duplicate, thanks for the effort though.

oh thank's

**Pull request closed without merging**
