### PR TITLE
types: remove expect error

### PR DESCRIPTION
**Pull request by imranbarbhuiya**
**Please describe the changes this PR makes and why it should be merged:**
I didn't expect the previous pr will be merged so fast lol. There is an issue with shapeshift typings which I'll fix but for now, we can use like this

- https://github.com/sapphiredev/shapeshift/pull/146

**Status and versioning classification:**

### CODE REVIEW

**Comment by iCrawl** [comment]
I'll leave the PR open, and we should just update it after a new patch version is released from shapeshift 👍

**Comment by Jiralite** [comment]
I believe this is no longer blocked: https://github.com/sapphiredev/shapeshift/releases/tag/v3.5.0

**Comment by imranbarbhuiya** [comment]
> I believe this is no longer blocked: [sapphiredev/shapeshift@`v3.5.0` (release)](https://github.com/sapphiredev/shapeshift/releases/tag/v3.5.0)

Waiting for `3.5.1` as there is an esm bug present in `3.5.0`

**Comment by imranbarbhuiya** [comment]
new version release and updated the pr. Also @iCrawl can you please do a new release of `/builder` after this pr merge to fix https://github.com/discordjs/discord.js/issues/8289 issues

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
