### PR TITLE
Update GuildChannel.js

### PR DESCRIPTION
**Pull request by Tylertron1998**
**Please describe the changes this PR makes and why it should be merged:**
Correctly documents the property name for the OverwriteData object.

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by iCrawl** [comment]
As https://discord.js.org/#/docs/main/master/typedef/GuildMemberResolvable and https://discord.js.org/#/docs/main/master/typedef/RoleResolvable suggest, it's more than just an `id` so this would be wrong.

**Comment by Tylertron1998** [comment]
The problem is that the property in the docs is wrong, from this: https://imgur.com/a/JdAh36T one would gather the correct code is:
```javascript
guild.channels.create('cool-channel', {
    overwrites: [{
        allowed: 'SEND_MESSAGES',
        memberOrRole: 'some_member_id'
        }]
});
```
is correct, where as it really is not. Not sure of a better JSDocs name, but the current one is far from clear.

**Comment by iCrawl** [comment]
#2817 should resolve this while also refactoring out the parts that were a bit iffy in the first place

**Comment by Tylertron1998** [comment]
Wonderful! Thanks.

**Pull request closed without merging**
