### PR TITLE
feat(guide): AI Agent to build faster with the library

### PR DESCRIPTION
**Pull request by samyakkkk**
**Please describe the changes this PR makes and why it should be merged:**
This PR introduces an AI agent that is trained on this repository and docs and can help us build anything with the library with just natual language - from our VSCode or with the web app.

**For example, just ask:**
"Create me a bot that responds with noted for every message when tagged"
"Update my existing code to show typing indicators"
"Handle the 2000 character limit error for my usecase"

https://github.com/user-attachments/assets/2164b4b1-5226-4b70-9c33-fd997ca0ce36

We recently used it to create our own Discord bot and the AI agent helped us do it in less than an hour. Hence sharing it with the community in case this is of help. 

- The agent will stay updated with any changes
- Free to use for developers
- Works form both VSCode and Web.

I'm happy to assist with any further changes. If you do not find this of help, please feel free to close the PR. thanks.

Try here without any setup: https://app.commanddash.io/agent/discordjs

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by almostSouji** [comment]
We are not adding ads to our repository, this is an interesting project nonetheless.

**Comment by samyakkkk** [comment]
thanks @almostSouji! I'm sorry, I did not meant to advertise. 

It genuinely helped us build super fast and our discord bot is now active. I'll be doing a few videos on it.

**Comment by rhaym-tech** [comment]
craziest one so far

**Comment by samyakkkk** [comment]
@rhaym-tech not sure you mean crazy good or crazy bad :)

**Pull request closed without merging**
