### PR TITLE
docs: fix streamdispatcher documentation

### PR DESCRIPTION
**Pull request by devdutchy**
**Please describe the changes this PR makes and why it should be merged:**
The current StreamDispatcher documentation still has Connection#playFile: https://github.com/discordjs/discord.js/blob/master/src/client/voice/dispatcher/StreamDispatcher.js#L25

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by hydrabolt** [comment]
Thanks for spotting this!

**Comment by iCrawl** [comment]
Should not update the typings in this PR.

**Comment by devdutchy** [comment]
> Should not update the typings in this PR.
Don't even know what happened there why it updated the typings

**Comment by iCrawl** [comment]
Well, you most likely did a recursive pull or your master branch wasn't up to date and you didn't check before committing.

**Comment by devdutchy** [comment]
That might've been it

**Comment by devdutchy** [comment]
Should be sorted now @iCrawl

**Pull request merged**
