### PR TITLE
fix(MessageEmbed): various typos and fixes

### PR DESCRIPTION
**Pull request by RDambrosio016**
**Please describe the changes this PR makes and why it should be merged:**
fixes some typos and other things

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by NotSugden** [comment]
shouldn't [this](https://github.com/discordjs/discord.js/blob/4ec01ddef56272f6bed23dd0eced8ea9851127b7/src/structures/MessageEmbed.js#L348) also be changed, currently says `Checks for valid field input and resolves strings`, however the function was renamed from `checkFields` to `normalizeFields`, so wouldn't `Normalizes for valid field input and resolves strings` (or validates maybe?) be better

**Comment by RDambrosio016** [comment]
fixed

**Comment by NotSugden** [comment]
You would need to make a new type for passing data into `addFields` as MessageEmbed#fields is an array of EmbedFields, and those fields will be `string`s, not `StringResolvable`s

**Comment by RDambrosio016** [comment]
out of the scope of this pr, i will open another one for typings

**Pull request merged**
