### PR TITLE
refactor(Util): remove convertToBuffer

### PR DESCRIPTION
**Pull request by vaporox**
**Please describe the changes this PR makes and why it should be merged:**

`Buffer.from()` accepts strings.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by papaia** [comment]
Those are private - this isn't breaking.

**Comment by tipakA** [comment]
If they are private, aren't they used internally in the lib?

**Comment by MattIPv4** [comment]
Neither are used anywhere in the lib.

**Comment by vaporox** [comment]
> Those are private - this isn't breaking.

JSDoc and typings contradict each other here, but it doesn't really matter since there probably won't be another v12 release anyway

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
