### PR TITLE
fix: remove `ActionRow.from()`

### PR DESCRIPTION
**Pull request by Syjalo**
**Please describe the changes this PR makes and why it should be merged:**
This PR removes `ActionRow.from()` since it contains incorrect docs, has no types and shouldn't be in a component.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Comment by vladfrangu** [comment]
Doesn't this go against the RFC?

**Comment by Jiralite** [comment]
Can you make a pull request to emit a deprecation warning to use the `ActionRowBuilder`'s static method instead?

**Review by vladfrangu — APPROVED** [review]

**Comment by CitTheDev** [comment]
> 

I just checked the `src/structures/ActionRow.js` and it does emit a deprecation warning.

**Review by Jiralite — APPROVED** [review]

**Comment by Jiralite** [comment]
Superseded by #10421.

**Pull request closed without merging**
