### PR TITLE
chore: add myself as contributor in package.json

### PR DESCRIPTION
**Pull request by kyranet**
**Please describe the changes this PR makes and why it should be merged:**

The contributors were probably copied from [discord.js-modules](https://github.com/discordjs/discord.js-modules/blob/7f1c9be817bbc6a4a11a726c952580dd3cb7b149/package.json#L22-L27), which somehow missed me, so I'm adding myself 😅

**Status and versioning classification:**

- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]
Poor Kyra left out

**Comment by iCrawl** [comment]
Hmmmmm.

**Comment by ToasterSticks** [comment]
LGTM!

**Comment by suneettipirneni** [comment]
Was this PR tested?

**Comment by kyranet** [comment]
Yes, it was. @suneettipirneni

**Review by SpaceEEC — APPROVED** [review]

**Pull request merged**
