### PR TITLE
Update publish-dev.yml

### PR DESCRIPTION
**Pull request by vijayymmeena**
**Please describe the changes this PR makes and why it should be merged:**

image

As you can see in the above image, there were four NPM releases for the same head in past 2 days. So, I would like to propose this PR to prevent this from happening and only release an update if it is necessary. 

**Status and versioning classification:**

- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by ImRodry** [comment]
Please don’t remove the date. We did this so that we could update more easily and dependabot could also pick up on new releases. I would really like to see this PR go forward but not by changing the versioning scheme

**Comment by oceanroleplay** [comment]
@ImRodry I wish the same, but I am not sure, how to make the if condition works with date. Perhaps someone can help about this.

**Comment by vladfrangu** [comment]
Well, the last part is the short commit hash, you can probably use that when checking if the version should be published (check latest from npm with HEAD or w/e in git)

**Comment by oceanroleplay** [comment]
@ImRodry this will work just perfect, what do you think?

**Comment by iCrawl** [comment]
You running a dev version in production is not our or my cup of tea.

Additionally, you could just let your dependabot update your deps once a week instead of looking for new ones every day.

**Comment by oceanroleplay** [comment]
@iCrawl just to confirm, you added this PR in milestone after you closed it. If that is correct, ignore.

**Pull request closed without merging**
