### PR TITLE
Type Checking for slash commands

### PR DESCRIPTION
**Pull request by Haiz14**
Asking if i should implement this feature

**Adding extra type checking properties** to `SlashCommandBuilder.StringOption`
- type()  // any popular type checking module on npm
- errorMesage() // optional, type BaseMessageCreateOptions

Upon receiving interaction discord.js will check the type, and send the error message as response to interaction.

### CODE REVIEW

**Comment by Haiz14** [comment]
discord.py has this feature i think

**Comment by Haiz14** [comment]
Sorry then, I wanted to ask if I do make a PR Thad does this, will you guys accept a PR?

**Comment by Haiz14** [comment]
I read somewhere, before doing a PR, first asl.

**Comment by almostSouji** [comment]
That's what discussions, the Discord server at discord.gg/djs or issues are for.
Don't create a PR adding an obsolete file with the request, and please be more detailed about what the functionality you want is.

**Pull request closed without merging**
