### PR TITLE
Fix the typing counter

### PR DESCRIPTION
**Pull request by DreamXZE**
Make the counter correctly typing track

**Please describe the changes this PR makes and why it should be merged:**
The counter when you type many command/message at once wasn't correctly tracked, this PR proposes a solution to fix this. 

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by SpaceEEC** [comment]
I don't think this PR changes anything.
You are storing the same reference to the object that is already in the map by adding that line.

**Comment by DreamXZE** [comment]
For my different test it changes. For having logged the counter in the starttyping and stoptyping function, I can say that the counter correctly didn't save and then display the wrong count. 
After making this change, it does display the correct count.
So I dunno

**Comment by SpaceEEC** [comment]
Could you share your test cases? Or anything on how to reproduce any incorrect behavior.

**Comment by DreamXZE** [comment]
I don't have anything now, but the best toobserve it is to have around ~0.5-1s of process between the start and the stop typing. On my end, I did process and send one picture. 
If you do 2 commands at the same time, one right after the other, you will never see the counter goes to 2 when he first reach the stop module.  After making this change, you will see the counter change correctly.

**Pull request closed without merging**
