### PR TITLE
Adjust name from Util to DiscordUtil publicly

### PR DESCRIPTION
**Pull request by TKDBB84**
Addresses open low priority issue: https://github.com/discordjs/discord.js/issues/2973 by renaming Util class to DiscordUtil throughout the codebase.

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
> not run but simple variable & path renames across the board

- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
> I intentionally left the existing Util & util exports to not break backward compatibility this could be considered for removal in the future.

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by devsnek** [comment]
you should fix intellij instead.

**Comment by TKDBB84** [comment]
i just saw a low hanging fruit issue, feel free to close the PR instead.  Won't hurt my feelings.

**Comment by Tenpi** [comment]
Why not just use the default export? No need to import Util.
```ts
import Discord from "discord.js"

Discord.Util.cleanCodeBlockContent("text")
```

Since 90% of the methods in Util are message related, why not call it `MessageUtil` instead? And you can move the shard related methods to `ShardClientUtil`. It's really unimportant, but I do agree on changing the name for better organization of all the methods.

**Comment by TKDBB84** [comment]
Happy to revamp it to `MessageUtil` if the consensus feels that's better, and move `fetchRecommendedShards` to ShardUtils (that looks to be the only shard method).  However reading through the list of methods, I feel like a lot of them are just generic Utils and not specifically message related, so I don't know that I'm 100% on board with `MessageUtil` but I'm a new contributor, and this barely counts as a contribution, so again, happy to default to the wisdom of the group.

Full disclosure, I'm also a IntelliJ user so I'd like to see this go through as well.

**Comment by devsnek** [comment]
how about `GeneralizedUtilitiesForDiscordJS`

**Comment by Tenpi** [comment]
> Happy to revamp it to `MessageUtil` if the consensus feels that's better, and move `fetchRecommendedShards` to ShardUtils (that looks to be the only shard method). However reading through the list of methods, I feel like a lot of them are just generic Utils and not specifically message related, so I don't know that I'm 100% on board with `MessageUtil` but I'm a new contributor, and this barely counts as a contribution, so again, happy to default to the wisdom of the group.
> 
> Full disclosure, I'm also a IntelliJ user so I'd like to see this go through as well.

I would just leave them in the Util class and then rename it to something like `GenericUtil` to solve your problem.

**Comment by TKDBB84** [comment]
Sorry I guess I'm confused between your two responses.  It sounded like you were for renaming it, but are recommending I just rename it locally or in my own fork?  Should I close this PR since it seems overall renaming the Util class is something not desired.

**Comment by jsmiith** [comment]
I just feel it is kinda unneeded.

**Comment by Skillz4Killz** [comment]
This is a very much needed change and a real issue to be honest. However, I think the PR is a bit overkill. The internal code of D.JS doesn't need to be changed at all. The solution is just a one-line addition in the index.js where you add the export of DiscordUtil. This allows anyone to export it as DiscordUtil without modifying the entire library

**Comment by TKDBB84** [comment]
> The internal code of D.JS doesn't need to be changed at all. The solution is just a one-line addition in the index.js where you add the export of DiscordUtil. This allows anyone to export it as DiscordUtil without modifying the entire library

Done, I had only changed all the internals as well so it was consistently named throughout.

**Comment by jsmiith** [comment]
Yeah. That's a lot better.

**Comment by didinele** [comment]
Okay so first off, I see discussion about this, but never any pros stated about it, so while you look for some pros, let me state the cons:

- pointless: Util is shorter to type, no point of importing `DiscordUtil`; just adds an extra alternative to `Util` and `util` and an extra line in the typings (not to mention this PR does not update typings at the moment) and besides what the original issue said about their editor not showing the d.js util class in autocomplete.. this doesn't really "fix" anything.. not like there's anything to "fix" about the library, but their editor, rather (this is pretty much a workaround)

- inconsistent across other packages: Most packages that export a Util class/namespace/whatever just name it util and export it that way

**Comment by TKDBB84** [comment]
> pointless
I might agree with this, it is primarily a QoL change for a few developers, so minimally pointful?

> Util is shorter to type,
I really hate this type of argument, if it was all about being shorter to type, we'd name all of our variables `x`, `y`, etc.  Naming is more about conveying information, "Util" when imported from the outside has minimal meaning.

> and an extra line in the typings (not to mention this PR does not update typings at the moment) 
unless I'm misunderstanding how typescript works, it would apply the defined Util type to the exported DiscordUtil as it's assigned directly to that, no additional types needed.

> this doesn't really "fix" anything
agreed! QoL change only, nothing wrong

> inconsistent across other packages: Most packages that export a Util class/namespace/whatever just name it util and export it that way
this one I'm less sure about, most of the major packages I've seen have moved away from a generic Util classes as they're generally considered an Anti-pattern, but I wasn't going to be brazen enough to propose nuking the whole class :-)

**Comment by didinele** [comment]
> I really hate this type of argument, if it was all about being shorter to type, we'd name all of our variables x, y, etc. Naming is more about conveying information, "Util" when imported from the outside has minimal meaning.

"conveying information" you say, yet I don't see "Discord" as a prefix bringing a lot of information

> unless I'm misunderstanding how typescript works, it would apply the defined Util type to the exported DiscordUtil as it's assigned directly to that, no additional types needed.

Now that I look at it, we're not even exporting `util` in the typings, in short terms we'd need to
```ts
export declare const util: typeof Util;
export declare const DiscordUtil: typeof Util;
```

**Comment by appellation** [comment]
> Also, you did reply to what I said but I still haven't really heard about any actual benefits despite it being a "QoL"

QoL is itself a benefit. Since this would seem to help many people and it comes at 0 cost to the library, I see no reason why this is a bad change.

**Comment by TKDBB84** [comment]
> Now that I look at it, we're not even exporting util in the typings, in short terms we'd need to
> export declare const util: typeof Util;
> export declare const DiscordUtil: typeof Util;

I don't think you need those?  Typescript should be able to infer the type from the assignment of declared `DiscordUtil`.

**Comment by kyranet** [comment]
Actually it'd be:

```typescript
export { Util as util };
export { Util as DiscordUtil };
```

**Comment by amishshah** [comment]
Thanks for the PR, but we had a discussion and decided to remove `util` as an alias of `Util` (53a1f8fcd4e333e60c32f9f51dc4062708eec207), so we won't be merging this PR as we'd just be adding yet another alias for `Util`.

**Pull request closed without merging**
