### PR TITLE
Add wildcard EventEmitter implementation and improve typings

### PR DESCRIPTION
**Pull request by ghost**
## Please describe the changes this PR makes and why it should be merged:
In this Pull Request I made a few changes to EventEmitters, as well as the typings.

__EventEmitters__:
Added a "Wildcard" EventEmitter implementation, which will emit a `'*'` event whenever any event is emitted. Example:
```js
client.on('*', event => {
  console.log(event); // { name: 'ready', data: [] }
});
```
This behavior __will not__ affect `error` events, and if one is emitted without an explicit handler, it will be thrown as usual.

As part of this, I added `eventemitter3` as an optional Peer Dependency, and updated several areas of the codebase to reflect this change, including, most notably, removing [`setMaxListeners()` etc. calls](https://github.com/primus/eventemitter3#eventemitter3) throughout the codebase. This is something that may or not be desired (as it breaks some edge cases which use these APIs), and can be easily reverted, should the rest of the PR be wanted. 

This feature is quite useful, as it allows for some very clean and simple `switch` statements to handle multiple events at the same time, without registering an additional listener (in theory, improving performance).

This feature should not have much of an impact on performance, if any; coupled with `eventemitter3`, there should even be noticeable performance gains.

__Typings__
I added all the necessary typings for the changes above, and also fixed a mistake at https://github.com/discordjs/discord.js/compare/master...Shinobu1337:master#diff-494415c3af35245ecae73f5d42d8b331L1014 (`on` changed to `once`).

## Status
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

## Semantic versioning classification:
 - [x] This PR changes the library's interface (methods or parameters added)
 - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
 - [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by devsnek** [comment]
👎 no need to slow down everything for wildcards

**Comment by appellation** [comment]
this was already declined in #2684 and wrapping it in extra (useless) functionality will not change that

**Comment by gloss-water** [comment]
couldn't you achieve this on the user side with the 'raw' event?

**Comment by appellation** [comment]
this is fundamentally different from the raw event. the raw event emits decoded websocket packets directly from the websocket, whereas this will emit every client event in an event named `*`.

**Pull request closed without merging**
