### PR TITLE
improve reliability of the browser/node check

### PR DESCRIPTION
**Pull request by vecchiotom**
**Please describe the changes this PR makes and why it should be merged:**
this fixes compatibility with applications that define the window object as an alias for global, up until now, the check was always returning true, causing various problems.

an example is FiveM, a popular GTAV Modification Framework, they define the window variable as an alias of the global object.

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by iCrawl** [comment]
We already had this discussion in #2224 somewhat.

Checking for process here is not a good solution because Electron will have process defined and you should really just use the browser build in Electron.

**Comment by gloss-water** [comment]
extremely blind guess but would checking for "this.window" instead resolve that? window.window always exists, and for browsers `this.window` should return the window no matter what

**Comment by iCrawl** [comment]
It's silly really. Checking for arbitrary globals to assure its a browser and in hindsight allow going against all practices. I'm really not a fan of this.

**Comment by iCrawl** [comment]
Okay so after digging a bit through the source of FiveM, all I can pretty much say is that you should probably just run your own fork with you desired changes in a separate branch and merge updates from upstream occasionally. 

The fact that FiveM runs their own fork of node and puts several things into the global namespace just makes it not feasible for us to adjust to every single case here.

**Comment by yuta0801** [comment]
@iCrawl 
> you should really just use the browser build in Electron.

Electron seems can access all functionality of Node.js, I think discord.js can run in electron with a few changes.
So should it still use browser build in electron? I was just interested in your thoughts

**Comment by iCrawl** [comment]
Yes, because you can already do that if you properly import it in the background process where node is actually running and communicate via IPC to the "frontend" part. This doesn't even need any changes on our side, its just people usually not knowing this or doing it the wrong way.

**Pull request closed without merging**
