### PR TITLE
Use generic types to create more accurate/adaptable typings

### PR DESCRIPTION
**Pull request by TomSputz**
**Please describe the changes this PR makes and why it should be merged:**

A rework to the nearly all the classes to support generic types. This is primarily to allow the client to be extended by frameworks without needing to re-type the entire library

```js
import { Client, Message, TextableChannel, TextChannel } from 'discord.js';

export class CommandClient extends Client {
  commands: { [key: string]: Command } = {};
}

export class Command {
  constructor(action: (msg: Message<TextableChannel<CommandClient>>) => any) {}
}

// Action.ts

import { Command } from 'command-module'

new Command(msg =>
  msg.channel.send('Hey')
    .then(msg => msg instanceof Array ? msg : msg.client.commands /* Exists */))

```

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by bdistin** [comment]
This seems to miss some stuff from Structures.extend(); For instance, you can have a CustomUser as your Message#author, but you have no generic to add your CustomUser to Message.

For speedy reference, the structures you can extend can be found here: https://github.com/discordjs/discord.js/blob/master/src/util/Structures.js#L72-L88

**Comment by 1Computer1** [comment]
I've already tried going the whole way as bdistin says, but was not successful due to mutually recursive types. If you could get it to work, that would be a great. However, right now, this PR is just a crutch if it can't support every custom structure, so I am against it.

**Comment by kyranet** [comment]
Is there anything module augmentation does not solve? #3068 was done to allow any TypeScript user to add augments as their rules dictate [here](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).

In my case, I'm using a framework augmenting discord.js while another package and my bot itself also do, and TypeScript handles it really nicely without needing to do this workaround.

**Comment by TomSputz** [comment]
I had to remove the generic relationships between Messages and Channels, but we are now able to type extensions to the Classes - a module doing that would look like this -

```js
import { Client, ExtendStructures } from 'discord.js';

export class CommandClient extends Client<MyStructureGroup> {
  commands: { [key: string]: Command } = {};
}
type MyStructureGroup = ExtendStructures<{
  Client: CommandClient
}>
export class Command {
  constructor(action: (msg: MyStructureGroup["Message"]) => any) {}
}

// Action.ts

import { Command } from 'command-module'

new Command(msg =>
  msg.channel.send('Hey')
    .then(msg => msg instanceof Array ? msg : msg.client.commands /* Exists */))
```
And on module augmentation - it seems like that was always the 'workaround' - In the example above, I'm not actually augmenting any of `discord.js`' classes. I'm simply instantiating them with the `CommandClient` as an argument, so using generic types reflects that better.

This also means that augmentations will not have to update when the discord.js interface changes, because they would be using the same types for any classes that weren't really extended.

I can't explain much else without knowing which library you're talking about, but for example in `discord-akairo` -
https://github.com/discord-akairo/discord-akairo/blob/master/src/index.d.ts#L15

The module augments the `Message` class, but this is a bad reflection of the actual javascript - the `discord.js` `Message` class does not have that property - it is simply something that is added to one of the instances by another method - https://github.com/discord-akairo/discord-akairo/blob/master/src/struct/commands/CommandHandler.js#L348

**Comment by appellation** [comment]
For all intents and purposes, the Message class has those extended properties when used with Structures.extend. While the original Message class is still technically available, it is never used again. While I'm a fan of more explicit typings, this seems to come at a pretty high complexity cost relative to module augmentation.

**Comment by TomSputz** [comment]
That's fair. This is definitely only making things slightly more accurate, and if it makes the typings too complex, then this doesn't suit the library

**Pull request closed without merging**
