### PR TITLE
SECURITYBOT

### PR DESCRIPTION
**Pull request by Rebazkoye**
SECURITYBOT

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

### CODE REVIEW

**Comment by Rebazkoye** [comment]
SECURITY

**Comment by Rebazkoye** [comment]
const { REST, Routes } = require('discord.js');

const commands = [
	{
		name: 'ping',
		description: 'Replies with Pong!',
	},
];

const rest = new REST({ version: '10' }).setToken('token');

(async () => {
	try {
		console.log('Started refreshing application (/) commands.');

		await rest.put(Routes.applicationGuildCommands(CLIENT_ID, GUILD_ID), { body: commands });

		console.log('Successfully reloaded application (/) commands.');
	} catch (error) {
		console.error(error);
	}
})();

**Comment by Rebazkoye** [comment]
Rebazkoye:patch-2

**Comment by almostSouji** [comment]
Please stop spamming our repository with unnecessary PRs and comments on other people's issues and threads.
This causes notifications to go out to a ton of people. If you are trying to test features, please do so in your own repositories instead.

We will consider blocking you from the repository if you continue.

**Pull request closed without merging**
