### PR TITLE
feat: allow deletion of ephemeral messages

### PR DESCRIPTION
**Pull request by monbrey**
* https://github.com/discord/discord-api-docs/pull/5570

Breaking because it no longer throws an error, but a bugfix because it shouldn't throw an error here anymore.

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by SpaceEEC — APPROVED** [review]

**Review by kyranet — COMMENTED** [review]
I'd argue that it's still https://github.com/discordjs/discord.js/labels/semver:major as-is because you're removing a property from `ErrorCodes`, which is a public and documented interface.

**Comment by SpaceEEC** [comment]
It should probably be deprecated instead then. 😅

**Comment by monbrey** [comment]
> I'd argue that it's still [ semver:major](https://github.com/discordjs/discord.js/labels/semver%3Amajor) as-is because you're removing a property from `ErrorCodes`, which is a public and documented interface.

I agree in theory and I'm happy to add it back, but the error can't be thrown by anything anymore.

**Comment by kyranet** [comment]
That is correct, but functions that read that property (e.g. error handlers) will break with this PR, that's why I consider it a breaking change.

Deprecating it is fine, however.

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Pull request merged**
