### PR TITLE
Change API coverage status due to decision not to implement RPC support

### PR DESCRIPTION
**Pull request by devsnek**
**Please describe the changes this PR makes and why it should be merged:**

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by liambagge** [comment]
he's correct, it doesn't support rich presences

**Comment by dragonfire535** [comment]
master does 🤔

**Comment by hydrabolt** [comment]
This is due to a decision that was made not to support RPC within discord.js if anybody is curious.

**Comment by gmedeadlystrike** [comment]
Can you clarify this. Will RPC just not be back-ported to the D.JS11 Stable Branch or will it not be present in the master / coming v12 release. If the later can you elaborate as to why?

**Comment by dragonfire535** [comment]
RPC will not be present in v12 as per my current knowledge, and is instead a separate module.

**Comment by devsnek** [comment]
@gmedeadlystrike its available as an officially supported module (currently in beta) as [discord-rpc](https://npmjs.org/discord-rpc)

**Pull request closed without merging**
