### PR TITLE
Fixes #2407

### LINKED ISSUE #2407: channel.setTopic(); cannot be used to set a topic to nothing
```js
channel.setTopic("");
// will refuse to set the topic, as with
channel.setTopic(null);

/*- discord.js version: stable
- node.js version: v9.7.1
- Operating system: Windows 10
note: issue is _only_ on stable*/

### PR DESCRIPTION
**Pull request by cdemirer**
**Please describe the changes this PR makes and why it should be merged:**
Small bugfix, issue #2407 

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Lewdcario** [comment]
We do not accept commits to the stable branch, there has also not been a consideration to make a patch version, so there is nowhere for this to go as it currently stands.

**Comment by cdemirer** [comment]
Oops, sorry for making a PR to stable branch. Also, do you mean that it's planned to make the next version v12 ? Sorry for the inconvenience, I'm novice on GitHub.

**Comment by Lewdcario** [comment]
This isn't an issue in Master branch.

**Comment by cdemirer** [comment]
I know it isn't an issue in master, I meant in my previous comment that I wondered if the next version will be 12.0.0, and that if any addition or fix should only be made for that version. It's probably yes, and my question was a bit unnecessary.

**Comment by Lewdcario** [comment]
12.0 is Master branch, in development, and it is already fixed there..

**Pull request closed without merging**
