### PR TITLE
Added premium parameter to user

### PR DESCRIPTION
**Pull request by JayRizuri**
**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the library's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by zaida04** [comment]
Might want to edit the title to reflect the changes you made, such as adding the Premium property.

**Comment by JayRizuri** [comment]
> **Please describe the changes this PR makes and why it should be merged:**
> 
> **Status**
> 
> * [ ] Code changes have been tested against the Discord API, or there are no code changes
> * [ ]  I know how to update typings and have done so, or typings don't need updating
> 
> **Semantic versioning classification:**
> 
> * [ ]  This PR changes the library's interface (methods or parameters added)
>   
>   * [ ]  This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
> * [ ]  This PR **only** includes non-code changes, like changes to documentation, README, etc.

**Comment by JayRizuri** [comment]
> Might want to edit the title to reflect the changes you made, such as adding the Premium property.

fixed

**Comment by zaida04** [comment]
As far as I'm aware, there's no documented `premium` property on a User.

**Comment by JayRizuri** [comment]
> As far as I'm aware, there's no documented `premium` property on a User.

I forgot to commit the user file
there is `premium_type`

**Comment by zaida04** [comment]
But that information is only available through OAuth2 requests. 

> Souji 06/19/2020
> premium_type is only received for oauth2 requests in the name of the user
> - discord.js just covers the bot, not the user API

**Comment by SpaceEEC** [comment]
> - [x] Code changes have been tested against the Discord API, or there are no code changes

What / how did you test and what results did you see?

As far as I am aware do bots not receive either of those fields.

**Comment by advaith1** [comment]
even if they did (they don't), this code wouldn't work anyway because it is checking for `data.premium_type` but then uses `data.premium`

**Comment by PyroTechniac** [comment]
Also, the typings are wrong, as it should be `premium?: string`, or premium needs to be assigned as `null` correctly

**Pull request closed without merging**
