### PR TITLE
fix(MessageDelete): when someone delete an embed message or empty message it returns empty value and it makes an error

### PR DESCRIPTION
**Pull request by dager-mohamed**
**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by almeidx** [comment]
How can a string/array have a negative length?

**Comment by kyranet** [comment]
Please provide a reproducible sample in which this would happen, I think the only way for this to happen is for a cosmic ray to flip up to 63 bits in a row 😅 

As aforementioned, arrays and strings cannot have negative length.

**Comment by dager-mohamed** [comment]
> How can a string/array have a negative length?

no because if someone deleted an embed message it returns empty content or someone  deleted an empty message

**Comment by kyranet** [comment]
Empty arrays and strings have a length of 0, not -1.

**Comment by dager-mohamed** [comment]
> Empty arrays and strings have a length of 0, not -1.

mhmm ok so I should make if it is equal zero right?

**Comment by kyranet** [comment]
No, you have yet to provide the error from discord.js (if any).

Otherwise, if the error is in the user's side (aka yours, and I think it most likely is), then this PR is invalid.

**Pull request closed without merging**
