### PR TITLE
Added an option to provide custom FFMPEG arguments.

### PR DESCRIPTION
**Pull request by VimHax**
**Please describe the changes this PR makes and why it should be merged:**

Added a new property to the `StreamOptions` object which gives users the ability to provide custom FFMPEG arguments or entirely replace the already existing FFMPEG arguments with their own. This gives more control over to users who are using FFMPEG for streaming.

**Status**

- [ * ] Code changes have been tested against the Discord API, or there are no code changes
- [ * ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ * ] This PR changes the library's interface (methods or parameters added)
- [   ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [   ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Deivu** [comment]
You could just use the opus directly yourself.

Refer to Hydra's comment in #2894

**Comment by VimHax** [comment]
Oh, I didn't know it was so simple to add a transcoder... I've googled a bunch but I couldn't find such a simple solution... I suppose that is the solution then to the problem I attempted to fix, however, this is also just a small and simple addition which you can use for small changes to the parameters, if you want something bigger, you can use a full blown transcoder. For my purpose, using such a transcoder is definitely overkill...

Also what about performance impacts? Wouldn't running a separate transcoder add some overhead versus just adding extra parameters to the already existing encoder?

**Comment by Deivu** [comment]
If you are already passing an opus stream, it won't, besides even you pass for example the ytdl stream to play, it would still do the same work of converting it so and forth behind the scenes, think of it that you are just doing it when you use prism-media directly. 

Refer to https://github.com/discordjs/discord.js/blob/master/src/client/voice/player/BasePlayer.js

Think of it as, you will just do the ffmpeg convertion, and pass it to `playPCMStream` which D.JS does when you pass an unknown stream to it

**Comment by amishshah** [comment]
I agree with everything @Deivu has said above! Customisation such as this is outside the scope of the library, but following the advice Deivu has given above should allow you to do what you're trying to do.

**Pull request closed without merging**
