### PR TITLE
fix(GuildChannel): Move createInvite() and fetchInvites() from GuildChannel to TextChannel/VoiceChannel

### PR DESCRIPTION
**Pull request by Monbrey**
When calling `fetchInvites()` on a CategoryChannel, the Discord API rejects the request with an "Unknown Channel" error.

As a result, `createInvite()` and `fetchInvites()` should not be on GuildChannel, as it is not usable on all classes that extend GuildChannel.

This PR moves `createInvite()` and `fetchInvites()` from GuildChannel to TextChannel and VoiceChannel, both of which the API accepts.
This also means that NewsChannel, which extends TextChannel will have the method but I haven't been able to test that.

**Status**
- [X] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [X] This PR changes the library's interface (methods or parameters added)
  - [X] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Monbrey** [comment]
Also swapped the order of some types because compu told me to

「随伴関手」compu 🍁: looks like the overload has to be swapped around

**Comment by MrJacz** [comment]
> Also swapped the order of some types because compu told me to
> 
> 「随伴関手」compu 🍁: looks like the overload has to be swapped around

Compu didnt tell you to

**Comment by Monbrey** [comment]
> Compu didnt tell you to

Did, but then suggested I revert it so I did

**Comment by kyranet** [comment]
This should probably use a mixin like `TextBasedChannel` to avoid code duplication.

And just curiosity, you can't create invite links in DM channels?

**Comment by Monbrey** [comment]
>This should probably use a mixin like TextBasedChannel to avoid code duplication.

Moving from TextChannel to TextBasedChannel would mean providing support for invites to be created/fetched on DMChannel also. The existing implementation was on GuildChannel, and would not have included those, so this was intended to be as like-for-like as possible while correcting the CategoryChannel error, as possibly StoreChannel too in theory.

The method would still need to be implemented separately on VoiceChannel either way.

>And just curiosity, you can't create invite links in DM channels?

I considered this - I think an Invite link can be to a group DMs but Im not sure how much discord.js intends to support that. That means the typing for `Invite#channel` might need to be corrected, but I intentionally didn't provide support for create/fetch in DMs, as above.

**Comment by almostSouji** [comment]
>And just curiosity, you can't create invite links in DM channels?  

You can indeed create invite links in DM channels for quite some time now.
However bots - last time i checked - could only create a channel for participants with their oauth2 tokens and not join or interact with this channel in any way.
IIRC that was introduced as part of game bridge in order to create group chats for game integrations.

So the only think needing to happen for bot support would be to revise Client#fetchInvite as that currently does not provide all information you get from the API (namely the channel being null)

**Comment by kyranet** [comment]
> Moving from TextChannel to TextBasedChannel would mean providing support for invites to be created/fetched on DMChannel also. 

I said a mixin like `TextBasedChannel`, not `TextBasedChannel`, so yeah, something like `InvitableChannel`.

> > And just curiosity, you can't create invite links in DM channels?
> 
> I considered this - I think an Invite link can be to a group DMs but Im not sure how much discord.js intends to support that. That means the typing for `Invite#channel` might need to be corrected, but I intentionally didn't provide support for create/fetch in DMs, as above.

I meant News Channels, sorry.

**Comment by Monbrey** [comment]
>I meant News Channels, sorry.

I don't have a NewsChannel to test with but they extend TextChannel so this should work if they do

**Comment by Monbrey** [comment]
> I said a mixin like `TextBasedChannel`, not `TextBasedChannel`, so yeah, something like `InvitableChannel`.

Looking into this, the approach doesn't seem to be used much through djs. `TextBasedChannel` and `Collector` are the only interfaces so far. Should we be trending towards this?

**Comment by Monbrey** [comment]
It was the linter that moved the region's, sorry about that.

I definitely see your point about there being way more to move, which makes this a much bigger conversation about how much actually can/should be inherited from a base class like `GuildChannel`.

I do think it seems we should be moving away from defining so much in `GuildChannel`, Discord seems to be continuing down the path of new/different channel types.

**Comment by Monbrey** [comment]
I think I'll close this for now - it doesn't fully solve the GuildChannel issue and it's still not clear if that's the approach you'd want to take. Will write it again in future if needed.

**Pull request closed without merging**
