### PR TITLE
fix(*): add missing imports for custom errors

### PR DESCRIPTION
**Pull request by iShibi**
**Please describe the changes this PR makes and why it should be merged:**

Since, custom errors have same names as native errors, they get left un-imported sometimes. Which results in errors that don't have any message in it. This PR fixes it by importing these errors in places where they are being used but were not imported.

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by SpaceEEC — DISMISSED** [review]
I found one more like these:
https://github.com/discordjs/discord.js/blob/dec191aa1e4f22690285ca06c6eee7e6086b2930/src/client/websocket/WebSocketManager.js#L6
and
https://github.com/discordjs/discord.js/blob/dec191aa1e4f22690285ca06c6eee7e6086b2930/src/client/websocket/WebSocketManager.js#L316

Considering we don't seem to be using the global `Error` anywhere in there, the imported class shouldn't be renamed and all occurrences of `DJSError` should be changed to `Error`.

**Comment by ckohen** [comment]
I don't actually see that error key in the messages file. Given it's only used to get the stack, it doesn't strictly need to be a DJSError but I so reason for it not to be. So just make sure to add the corresponding message

**Comment by iShibi** [comment]
Done. btw I took an easy way out by just copying the same message. 😆

**Review by kyranet — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Comment by vladfrangu** [comment]
> I don't actually see that error key in the messages file. Given it's only used to get the stack, it doesn't strictly need to be a DJSError but I see no reason for it not to be. So just make sure to add the corresponding message

Because there is no key for that error, in fact it could even be empty for all it matters :D

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
