### PR TITLE
refactor(RichPresenceAssets): Remove non-breaking custom image support

### PR DESCRIPTION
**Pull request by Jiralite**
Due to #7635, YouTube has been removed from parsing here. The rest will be removed in version 14.

### CODE REVIEW

**Comment by ImRodry** [comment]
“remove support” and “non-breaking” don’t really go well together, how is this not breaking?

**Comment by Jiralite** [comment]
This isn't in stable.

**Comment by ImRodry** [comment]
It’s still v13, wdym

**Comment by imranbarbhuiya** [comment]
> It’s still v13, wdym

he mean yt isn't in `v13.6` release only in `v13` branch for `v13.7` release so it can be removed.

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Pull request merged**
