### PR TITLE
Client.login() should return a Client, not the token provided

### PR DESCRIPTION
**Pull request by kyle2000yt**
**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [ ] Code changes have been tested against the Discord API, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by RDambrosio016** [comment]
This is a breaking change, therefore it is not able to be merged.

**Comment by didinele** [comment]
The PR template is there for a reason.

Why? What is the motivation behind this? This seems absolutely pointless.

**Comment by LxveFades** [comment]
I don't see a point in returning the Client instance over the token once the Promise has been resolved. And if it indeed should return the instance over the token, typings would need to be updated.

:-1: from me.

**Comment by vzwGrey** [comment]
To expand on what the guys above me were saying: This repository will no longer accept breaking changes. All breaking changes will need to be PRed to [discord.js-next](https://github.com/discordjs/discord.js-next) where the future version 13 of discord.js will live.
As you can probably see that repo is not quite ready yet so you will have to wait a short while until you can request your change.

And yes, when you make your new PR please fill in the template properly (write a short blurb about why the PR should be merged and tick the items properly by putting an `x` inbetween the relevant `[ ]`).

**Pull request closed without merging**
