### PR TITLE
feat(WebSocketManager): let identify throw on depleted limits

### LINKED ISSUE #5282: Throw when identify limit is fully depleted instead of delaying
**Is your feature request related to a problem? Please describe.**

Client stalls indefinitely when identify limit is depleted. To find the source of the misbehavior users currently have to go great length (adding a listener for the `"debug"` event) to find out what's stalling their bot

**Describe the ideal solution**

Instead of just preventing going over the limit, throw an error

**Describe alternatives you've considered**

(maybe optionally restore the old behavior with explicit opt-in, the default should be throwing - noone wants to wait for 24h for a successful login, let's be real)

**Additional context**

### PR DESCRIPTION
**Pull request by almostSouji**
**Please describe the changes this PR makes and why it should be merged:**

⚠️ closes #5282
✔️  ~~untested~~ now tested by @vladfrangu 

**Status and versioning classification:**

- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Comment by vladfrangu** [comment]
This doesn't seem to be a major change at all? We could argue the previous behavior was unintended, and this is a "bug fix"

Could we at least keep the log that logs the limit on connect?

**Comment by iCrawl** [comment]
We can absolutely not argue that, and considering there is no v12 release anymore it's not really relevant.

**Comment by Wilco2998** [comment]
could this also be applied to more of the functionality of the library like when changing something about a role

**Comment by monbrey** [comment]
> 
> 
> could this also be applied to more of the functionality of the library like when changing something about a role>
> I got a ratelimit when trying to change a role color too many times

When developing code that respects rate limits and works with them, the queuing behaviour is far more useful than throwing a rejection. The identify limit is the exception to this.

When writing code that completely *disrepects* Discord's rate limits with actions they specifically discourage, like rainbow roles, you should be reconsidering your bots features.

**Review by vladfrangu — CHANGES_REQUESTED** [review]
Can you please add the debug log back at least? 🙏

**Review by vladfrangu — APPROVED** [review]
Pls ignore my previous review, my brain is currently lagging behind a LOT. LGTM

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Comment by SpaceEEC** [comment]
`WebSocketManager#sessionStartLimit` seems to be only assigned to once when calling `connect`, which does not seem to be called again.
If I'm not wrong with that, that property could probably be removed, as it will just go stale.

**Pull request merged**
