### PR TITLE
fix(SlashCommandBuilder): import `Permissions` correctly

### LINKED ISSUE #7920: Bad typing for `.setDefaultMemberPermissions()`
### Which package is this bug report for?

builders

### Issue description

I'm not exactly sure where this type is getting messed up, but the `permissions` parameter on `setDefaultMemberPermissions()` is getting typed as `Permissions` from the built in `typescript/lib/lib.dom.d.ts` rather than `Permissions` from `discord-api-types` (where `type Permissions = string`).

This means that `.setDefaultMemberPermissions()` complains about the passed argument type no matter what.

### Code sample

_No response_

### Package version

0.14.0-dev.1652443433-d522320

### Node.js version

v16.13.0

### Operating system

macOS

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

d522320

### PR DESCRIPTION
**Pull request by vladfrangu**
**Please describe the changes this PR makes and why it should be merged:**

Closes #7920 

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by KhafraDev** [comment]
Is it possible to remove the dom types from /rest completely?

```
../../../AppData/Roaming/npm/node_modules/typescript/lib/lib.dom.d.ts
  Library referenced via 'dom' from file 'node_modules/@discordjs/rest/dist/index.d.ts'
```

(using `tsc --explainFiles`)

**Comment by vladfrangu** [comment]
Not related to this PR soooo 🤷 
Check why they're used in rest and see if they can be removed

**Review by favna — APPROVED** [review]

**Review by twisttaan — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Comment by SuperchupuDev** [comment]
Would it be possible to support `bigint` in the method too? It works already and it's really useful because `PermissionFlagsBits` returns a BigInt

**Comment by vladfrangu** [comment]
Woops. Nice catch - forgot I made the validator support bigints but not the actual method types

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
