### PR TITLE
chore v13: update version in package-lock

### PR DESCRIPTION
**Pull request by jaw0r3k**
**Please describe the changes this PR makes and why it should be merged:**
- Looks like somebody forgot to do it

**Status and versioning classification:**
- It only includes package-lock.json change

### CODE REVIEW

**Comment by Qjuh** [comment]
This PR is useless, as once it‘ll make it into a release it won‘t be accurate anymore anyway…

**Comment by jaw0r3k** [comment]
> This PR is useless, as once it‘ll make it into a release it won‘t be accurate anymore anyway…

but until if there isnt a new release it is okey

**Comment by Qjuh** [comment]
No, it‘s also useless until then, because this PR won‘t magically make its way back into the already released v13.12.0

**Comment by imranbarbhuiya** [comment]
`package-lock.json` doesn't get published in npm

**Pull request closed without merging**
