### PR TITLE
feat: add API v10 support

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

~~Pending next -types release~~
released

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by almeidx** [comment]
Looks like there has been a -types release

**Review by vladfrangu — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Review by Mysterious-Dev — APPROVED** [review]

**Comment by kyranet** [comment]
This PR needs quite the rebase.

**Review by kyranet — APPROVED** [review]
Only thing is that I would bump discord-api-types to 0.27.3 to not conflict with #7023, but it's fine otherwise.

**Review by iCrawl — APPROVED** [review]

**Comment by iCrawl** [comment]
This needs a rebase.

**Comment by iCrawl** [comment]
This needs a rebase.

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
