### PR TITLE
feat(ApplicationCommand): add `min_length` and `max_length` for string option (v13)

### PR DESCRIPTION
**Pull request by Mateo-tem**
**Please describe the changes this PR makes and why it should be merged:**

Backports #8215 to v13.

**Status and versioning classification:**

### CODE REVIEW

**Review by Jiralite — CHANGES_REQUESTED** [review]
There is also no documentation here.

**Comment by Mateo-tem** [comment]
> There is also no documentation here.

Now added!

**Review by Mateo-tem — COMMENTED** [review]
Should I change this? Or it's not important?
(The upstream PR had that and I notice that little errors after it was merged)

**Comment by Jiralite** [comment]
> Should I change this? Or it's not important? (The upstream PR had that and I notice those little errors after it was merged)

Do all of them!

**Comment by Mateo-tem** [comment]
> > Should I change this? Or it's not important? (The upstream PR had that and I notice those little errors after it was merged)
> 
> Do all of them!

Done!

**Comment by Mateo-tem** [comment]
Oh, I noticed that the `min_length` and `max_length` fields are missing in ApplicationCommandOptionData, in v14. I'm going to open a PR to add it here.

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
