### PR TITLE
Allow suppressing of embeds on messages

### PR DESCRIPTION
**Pull request by Renari**
**Please describe the changes this PR makes and why it should be merged:**

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by RDambrosio016** [comment]
This should be marked as semver minor in the template because it adds parameters and methods

**Comment by Renari** [comment]
I noticed one issue with this implementation, if the suppress embeds flag is set before an embed is processed on discords side. The embed will happen anyway, sending the flag again following the embed will remove it. I'm not entirely sure how to handle that except to implement something along the lines of `await embed`.

**Comment by Monbrey** [comment]
Fair point, though I can't think of a reason a developer would be sending this flag before Discord has processed the embed. 

Seems more like an implementation issue to me.

**Comment by Renari** [comment]
I agree but I feel that a way should be offered to handle that. For example if this message was sent to discord.
image

It embeds the users avatar and the page title. This isn't very useful. If I wanted to grab meaningful data for this commit and have the bot post it instead of this embed. The implementation problem then becomes that I have an indeterminate amount of time to wait for discord to process and place this embed to remove it. Thus I believe something similar to `message.awaitReactions` should be offered. `message.awaitEmbed`.

**Comment by Monbrey** [comment]
The `messageUpdate` event will fire when an embed is rendered by Discord - could that not be used in this scenario?

**Comment by Renari** [comment]
Yeah that would work, ignore me.

**Comment by Renari** [comment]
On further inspection `messageUpdate` does not appear to be triggering for these embeds.

**Comment by Renari** [comment]
Interesting, so I tested this using github, twitter and pixiv. Pasting a pixiv image does not trigger `messageUpdate` when the embed is added. However for github and twitter `messageUpdate` is triggered.

**Comment by Monbrey** [comment]
I'm not able to reproduce that with what I think is a Pixiv URL - can you please provide some examples of the ones you're testing with?

**Comment by Renari** [comment]
Yeah I posted the issue here: https://github.com/discordjs/discord.js/issues/3685

It seems what happens is if the image was posted recently it sends the message with the embed attached already with the new message event. If it isn't cached then you get a `messageUpdate` event triggered.

**Comment by SpaceEEC** [comment]
Closing this PR in favor of #3795.

**Pull request closed without merging**
