### PR TITLE
types(MessageSelectMenu): fix typings

### PR DESCRIPTION
**Pull request by kikorp78**
**Please describe the changes this PR makes and why it should be merged:**
I noticed a small issue, although I am not sure about it.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by SpaceEEC — APPROVED** [review]

**Review by ImRodry — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Comment by DTrombett** [comment]
There's also an error in the docs which shows `disabled` nullable while it isn't. I don't know if you can fix it in this PR...

**Comment by kikorp78** [comment]
> There's also an error in the docs which show `disabled` nullable while it isn't. I don't know if you can fix it in this PR...

I found that piece of code yeah, but can't you suggest changes or something so that I can be sure if that's what you really mean?

**Comment by ImRodry** [comment]
You can't suggest changes on unaffected files. Just remove the nullable tag

**Comment by kikorp78** [comment]
That is also a case with MessageButton class for example.

**Review by iCrawl — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
