### PR TITLE
test(webhooktest): replace unused url

### PR DESCRIPTION
**Pull request by green1052**
**Please describe the changes this PR makes and why it should be merged:**

I think lolisafe.moe has been replaced by chibisafe.moe

lolisafe.moe is redirect to chibisafe.moe

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by ImRodry** [comment]
Both still work tho

**Comment by green1052** [comment]
lolisafe.moe redirect to chibisafe.moe

I think that using a redirected address is inefficient.

so i pr this

**Comment by green1052** [comment]
If you think useless my code
please close my pr

thx

**Comment by DTrombett** [comment]
They're just example links... It doesn't matter actually.

**Comment by green1052** [comment]
ok thx

**Pull request closed without merging**
