### PR TITLE
types(MessageOptions): remove split?: false overload

### PR DESCRIPTION
**Pull request by monbrey**
Having overloads on MessageOptions for both `{ split?: false }` and `{ split: true | SplitOptions }` was causing TS to error - these  types were seemingly incompatible with either each other, or the base `split?: boolean | SplitOptions` typing.
As a result `MessageOptions` could not be passed to `send` methods.

I don't believe we need the `false` state, because it's only the presence of `true | SplitOptions` that would actually change the return type. I could be wrong though, but this does remove the error.

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by monbrey** [comment]
...but now one of the tests fails, so I'm going to re-assess

**Comment by monbrey** [comment]
Yeah this is beyond my understanding of types after all, closing

**Comment by suneettipirneni** [comment]
I was wondering if this is still being considered, I've often had to make type alias to avoid having to type `MessageOptions & { split?: false }`. It would be awesome if this typing was consolidated.

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Comment by SpaceEEC** [comment]
I think the more correct way to go about this is to keep the original overloads and make the new ones return `Message | Message[]` (or `RawMessage | RawMessage[]`, or both), since those overloads don't know whether `split` is present or not.

The `index.ts` (the one without .d`), should be updated to include "tests" for those, so we hopefully don't break it straight away again.

~~Simpler send overloads anyone?~~

**Comment by iCrawl** [comment]
This needs a rebase.

**Comment by monbrey** [comment]
> I think the more correct way to go about this is to keep the original overloads and make the new ones return `Message | Message[]` (or `RawMessage | RawMessage[]`, or both), since those overloads don't know whether `split` is present or not.

We do though, don't we? The first overload confirms that if `split` is either `true` or `SplitOptions` then it returns a Message[]. The only other values TypeScript could allow is either explicit false, or leaving it out entirely.

**Comment by ImRodry** [comment]
This will no longer be needed if #5918 is merged

**Comment by monbrey** [comment]
> This will no longer be needed if #5918 is merged

We know

**Pull request closed without merging**
