### PR TITLE
Handle Memory Leak

### PR DESCRIPTION
**Pull request by Nigelrex**
Handle Memory Leak that closes the node process if the process has hit the max memory limit

**Please describe the changes this PR makes and why it should be merged:**
Added a `.catch()` to handle and close the process before the process starts to eat up a ton of memory in a few minutes UP to 2GB

**Status and versioning classification:**
This PR nomore includes breaking changes (methods removed or renamed, parameters moved or removed)

typings don't need updating

https://user-images.githubusercontent.com/75080457/143230670-41746d78-1fa0-4499-b601-e110169cbadc.mp4

### CODE REVIEW

**Comment by Nigelrex** [comment]
I didn't wnat to do the full testing my here you go, I also made those changes!

**Comment by Nigelrex** [comment]
I didn't want to do the full testing my here you go, I also made those changes!

**Comment by vladfrangu** [comment]
This Pull request:

- reverts changes that were made to be compatible with the newer API features
- stylistic changes that our linter will scream at
- kills the process at any error encountered by node fetch, which is highly undesirable

If you're encountering ram issues while sending files, maybe try using read streams instead, I think we handle those. If we don't, that's what should be implemented instead

**Comment by iCrawl** [comment]
Additionally, to the mentioned things from Vlad, this is a horrible way to measure your RAM usage, the underlying issue is a completely different.

To fix this all you must do is simply make sure you have an active DNS resolvable record

**Comment by Nigelrex** [comment]
B r u h, I sent a video and showed that if there was a connection error your RAM usage by the nodejs process goes up untill it exceeds the limit and then it crashes

**Pull request closed without merging**
