### PR TITLE
typings(Channel): add literal types for channel types

### PR DESCRIPTION
**Pull request by pizzafox**
**Please describe the changes this PR makes and why it should be merged:**

This change allows the TypeScript compiler to use `Channel.type` as a type guard.

For JavaScript users, this will have no real impact (other than autocomplete by editors).
However, TypeScript users will be able to leverage the [TypeScript compiler's type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types) feature to know what type of channel (ex. `TextChannel`) you have based on its `type` property.

```ts
if (myChannel.type === 'text') {
  // myChannel is a TextChannel
} else {
  // myChannel is not a TextChannel
}
```

**Status**
- [ ] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by NotSugden** [comment]
this also fixes #2957

**Comment by pizzafox** [comment]
Requesting a review from @SpaceEEC because they were involved in issue #2957

**Comment by didinele** [comment]
This is not being done the "correct" way, should probably use the ChannelType enum declared at the very top of the declarations file.

**Comment by iCrawl** [comment]
#3808

**Pull request closed without merging**
