### PR TITLE
chore: bump deps

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**
**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by ImRodry** [comment]
still no discord-api-types 😢

**Comment by vladfrangu** [comment]
> still no discord-api-types 😢 

* *Yet*

**Comment by kyranet** [comment]
You have merge conflicts, and please bump `discord-api-types` now that it got a new release 👀

**Comment by suneettipirneni** [comment]
Done

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
