### PR TITLE
feat(Guild): add ROLE_SUBSCRIPTIONS_ENABLED guild feature

### PR DESCRIPTION
**Pull request by iShibi**
**Please describe the changes this PR makes and why it should be merged:**

- discord/discord-api-docs#3823
- discord/discord-api-docs#3846

**Status and versioning classification:**
- I know how to update typings and have done so

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Review by ImRodry — CHANGES_REQUESTED** [review]
~~@iShibi please undo commit https://github.com/iShibi/discord.js/commit/93a40090fe2504c62c7d6747ed94e071d75d81d3 as this was something that was changed in #6299 and makes it easier to spot new features (they currently follow the order in Discord's API docs, if you want, you should make a PR to them to change the order)~~

**Comment by vladfrangu** [comment]
Check the linked PR, it literally sorts them alphabetically 👀

**Comment by iShibi** [comment]
Old upstream PR got closed, the new follow up PR seems to add some more stuff. Hence, converting this to a draft for now

**Comment by almeidx** [comment]
No longer needed as of #7397

**Pull request closed without merging**
