### PR TITLE
FIX YOUR ERRORS

### PR DESCRIPTION
**Pull request by callumok2004**
**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

```
0|index    | /root/discordbot/node_modules/discord.js/src/client/Client.js:40
0|index    |     } catch {
0|index    |             ^
0|index    | 
0|index    | SyntaxError: Unexpected token {
0|index    |     at createScript (vm.js:80:10)
0|index    |     at Object.runInThisContext (vm.js:139:10)
0|index    |     at Module._compile (module.js:616:28)
0|index    |     at Object.Module._extensions..js (module.js:663:10)
0|index    |     at Module.load (module.js:565:32)
0|index    |     at tryModuleLoad (module.js:505:12)
0|index    |     at Function.Module._load (module.js:497:3)
0|index    |     at Module.require (module.js:596:17)
0|index    |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|index    |     at require (internal/module.js:11:18)
```

### CODE REVIEW

**Comment by tipakA** [comment]
Please update your node instead. You need at least node 12 as per readme.

**Comment by callumok2004** [comment]
am using node 12

**Comment by callumok2004** [comment]
```
root@us:~/discordbot# node -v
v12.16.1
```

**Comment by callumok2004** [comment]
I have been having this issue for 2 weeks !!

**Comment by callumok2004** [comment]
How is it invalid?

**Comment by iCrawl** [comment]
The `} catch {` syntax is valid since Node v11.

https://node.green/#ES2019-misc-optional-catch-binding

**Comment by callumok2004** [comment]
Then how do I fix it? Why am I getting the error if I already have version 12.

**Comment by vladfrangu** [comment]
There is no way for this error to happen if you're running it with nodejs >= 11.

Add a `console.log(process.version)` before require-ing discord.js and see what it logs.

**Comment by callumok2004** [comment]
v12.16.1

**Comment by Fyko** [comment]
Going out on a limb here,

If you've upgraded your Node.js version with nvm you may need to run `nvm use` to switch to the new verion.

**Pull request closed without merging**
