### PR TITLE
feat(Emoji): support more extensions in `url()` function

### PR DESCRIPTION
**Pull request by dager-mohamed**
**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

### CODE REVIEW

**Comment by monbrey** [comment]
This is just incorrect. The line of code you modified is a ternary, providing .gif if animated and .png if not. 

It's not a list of options which to be selected from.

**Comment by dager-mohamed** [comment]
so... , i understand only 50% of you said, anyway the problem is from my javascript code or all idea is wrong or what :rofl:

**Comment by monbrey** [comment]
I understand the idea is to support additional formats, because static emojis aren't always PNG.

The code you wrote does not do that, at all. It will continue to always pass .PNG as it's the first one and it's a truthy value. Nothing you've written allows the user to select a format.

**Comment by dager-mohamed** [comment]
> 

ahaa ok , i will delete this PR and when I finish I will do another PR

**Pull request closed without merging**
