### PR TITLE
docs: add typescript topic

### PR DESCRIPTION
**Pull request by Iffabled**
**Please describe the changes this PR makes and why it should be merged:**
This pull request adds a topic explaining how to use discord.js with TypeScript.

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Monbrey** [comment]
This... doesn't have any TypeScript in it

**Comment by Iffabled** [comment]
> This... doesn't have any TypeScript in it

The provided examples are written in TypeScript.

**Comment by Monbrey** [comment]
They may have been written in `.ts` file, but you aren't demonstrating anything unique to the superset that is TS.
All this demonstrates is that any valid JS (which is what you've written) is also valid in TS.

**Comment by Iffabled** [comment]
> They may have been written in `.ts` file, but you aren't demonstrating anything unique to the superset that is TS.

The primary "selling point" of TypeScript is it's type checking.

**Comment by Tenpi** [comment]
While all Javascript is also valid Typescript, I think you should focus more on Typescript-only features such as adding **typings** for function parameters and variables. 

If you aren't familiar with Typescript, a great place to start is with the official documentation: https://www.typescriptlang.org/docs/home.html

**Comment by PyroTechniac** [comment]
This should also follow the linting rules of the standard lib (So no line breaks between function definition and open bracket)

**Comment by iCrawl** [comment]
In it's current state I honestly don't think this adds anything subsential.

**Pull request closed without merging**
