### PR TITLE
Remove Clyde because no one likes Clyde

### PR DESCRIPTION
**Pull request by MrJacz**
**Please describe the changes this PR makes and why it should be merged:**
Remove Clyde, This being a meme PR from Gus a while ago there isn't any reason for Clyde to be in the User's collection

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by GummiWummiBear** [comment]
good meme

**Comment by HorizonTM** [comment]
Not nice. i LIKE clyde okay

**Comment by RuyiLi** [comment]
clyde did nothing wrong

**Comment by loserVEVO** [comment]
good't

**Comment by MrJacz** [comment]
Let's be serious, stop memeing. thanks

**Comment by dragonfire535** [comment]
Being serious, I see no real reason to remove Clyde, he is considered an actual user by the client.

**Comment by bdistin** [comment]
Being serious, I see no real reason to keep Clyde, he is __NOT__ considered an actual user by the api.

**Pull request closed without merging**
