### PR TITLE
feat(next): export missing packages

### PR DESCRIPTION
**Pull request by dager-mohamed**
**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

I discovered that a number of packages were not properly exported to the `next` package in the project, so I created new files within the exports folder and exported the missing packages. This ensures that all necessary packages are easily accessible and can be utilized by developers.

**Please move lines that apply to you out of the comment:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by Syjalo** [comment]
Some packages are private and doesn't published on npm. Others aren't needed while working with discord.js.

**Comment by dager-mohamed** [comment]
> Some packages are private and aren't published on npm. Others aren't needed when working with discord.js.

I removed the private packages,
but some packages may not currently be needed, they may become necessary in the future

**Review by kyranet — COMMENTED** [review]
For future reference, you must use `yarn` to update the `yarn.lock` and link dependencies properly.

The code is also not formatted (missing semicolons).

Also, `/next` is intended to be for packages `discord.js` will use, and those 3 (/brokers, /proxy, /voice) are not part of those — they're optional.

**Comment by dager-mohamed** [comment]
> 

got it

**Pull request closed without merging**
