### PR TITLE
fix(voice): Rewrite entersState

### PR DESCRIPTION
**Pull request by PapiOphidian**
entersState currently uses internal node modules and abort controllers which locks the thread and causes an AbortError to be thrown. This is remedied by having the user create their own entersState function and using that instead - which they shouldn't have to do. This PR rewrites entersState to be more sensible in design and is not affected by thread locking.

Cons: Usage of AbortControllers has been removed in favor of only millisecond timeouts. abortAfter and related tests have been removed/altered.

**Status and versioning classification:**
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Comment by PapiOphidian** [comment]
I accidentally botched my commit message

**Comment by vladfrangu** [comment]
How exactly is this any better? And how is it *thread blocking* in an async context? 🤔 To me this seems like removing support for AbortSignals for no reason (and they're also used in *many* other places without issues - see rest)

**Comment by PapiOphidian** [comment]
AbortControllers aren't the issue, more of just using node internal modules. What I and a lot of other people have noticed is that even with ideal network conditions and system responsiveness, AbortErrors were super common (I host on a gigabit connection and all of my music logic is contained in worker_threads. As much as I hate to say that my bot doesn't get used often, it's relevant to this). Someone in the discord.js guild mentioned that the issue was entersState and from there, a lot of people who had AbortError issues were told to make their own entersState function which has fixed the AbortError issues.

The function I have proposed for overwriting is adapted from https://github.com/AmandaDiscord/Volcano/blob/main/src/worker.ts#L80 which includes an error stating that the resource has not entered the state in time. Throughout the entire uptime of all of my nodes of this project, which is however long ago the first commit adding that function is, I have not had a single error stating that the resource hasn't entered the state in time.

The only logical conclusion I and others can make is that the official implementation is flawed.

**Comment by Jiralite** [comment]
There seems to be a formatting issue. `yarn format` should resolve that?

**Comment by PapiOphidian** [comment]
I'm not too sure about that one
```
...
discord.js:format: discord.js-patch\packages\discord.js\src\client\websocket\WebSocketManager.js
discord.js:format:   322:5  warning  Unexpected 'todo' comment: 'TODO: Make a util for getting a stack'  no-warning-comments
discord.js:format:
discord.js:format: discord.js-patch\packages\discord.js\src\structures\ApplicationCommand.js
discord.js:format:   380:7  warning  Unexpected 'todo' comment: 'TODO: remove ?? 0 on each when nullable'  no-warning-comments
discord.js:format:
discord.js:format: discord.js-patch\packages\discord.js\src\structures\GuildScheduledEvent.js
discord.js:format:   323:3  warning  Unexpected 'todo' comment: 'TODO: scheduledEndTime gets reset on...'  no-warning-comments
discord.js:format:
discord.js:format: ✖ 3 problems (0 errors, 3 warnings)
discord.js:format:

 Tasks:    11 successful, 11 total
Cached:    11 cached, 11 total
  Time:    858ms >>> FULL TURBO


> git status
On branch 1
Your branch is up to date with 'origin/1'.

nothing to commit, working tree clean

>
```

**Comment by Jiralite** [comment]
Can you try updating your branch and run it again?

**Comment by PapiOphidian** [comment]
Yeah that didn't work

**Comment by PapiOphidian** [comment]
So yeah. Looks like any change I do, I run lint once and it tells me not good, but I run it again and it says it's fine

**Comment by Jiralite** [comment]
Update your branch once more to account for #8279. It seems the cache caused issues here. Running `yarn format` should finally resolve this for you.

**Comment by PapiOphidian** [comment]
Thanks

**Comment by PapiOphidian** [comment]
Why was this closed?

**Comment by PapiOphidian** [comment]
I would have liked some feedback as to why this was closed such as if the loss of AbortControllers is unacceptable or if my code needed changes - I can always add more commits. You may even call me an idiot given there is a valid reason. However, this is a valid issue which does not make the out of box experience great and I would at least like an alternative to be proposed or the issue be properly addressed.

**Pull request closed without merging**
