### PR TITLE
Update typings for send() function to return an array only if split i…

### PR DESCRIPTION
**Pull request by n3oney**
…s true.

**Please describe the changes this PR makes and why it should be merged:**

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by bdistin** [comment]
Dupe of #3128

**Comment by Monbrey** [comment]
As we've been discussing on Discord, this typing isn't correct unless you also modify the way the send function works to *always* return an Array if the split option is passed.

Currently it won't - it can still return `Message` if the length is less than the split length.

**Comment by didinele** [comment]
I mean...

You threw the rest of the options out the window, `MessageOptions | MessageAdditions` is more than just `split`, if you manage to implement this while also keeping the rest of the options then sure

**Comment by appellation** [comment]
> 
> 
> As we've been discussing on Discord, this typing isn't correct unless you also modify the way the send function works to _always_ return an Array if the split option is passed.
> 
> Currently it won't - it can still return `Message` if the length is less than the split length.

This has already been done by #3035, so these could be merged together.

**Comment by n3oney** [comment]
Well, i guess the best option is to merge them together.

**Pull request closed without merging**
