### PR TITLE
feat(Message#Reply): Added the new reply.

### PR DESCRIPTION
**Pull request by fagnersales**
**Please describe the changes this PR makes and why it should be merged:**
Brings the new reply into Message#Reply.

Changes made by me and @Nathankayk

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Vaporox** [comment]
#4874 is already implementing the new reply feature.

**Comment by kylerchin** [comment]
F in the chat for everyone who wrote code but then realized that another PR was already working on it

**Comment by 433452523523532** [comment]
hyhhh

**Comment by 433452523523532** [comment]
lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll

**Pull request closed without merging**
