### PR TITLE
Channel Types Update

### PR DESCRIPTION
**Pull request by jpbberry**
**Please describe the changes this PR makes and why it should be merged:**
This will add a new ChannelTypes object in place of the .type on Channel. This will allow for a cleaner experience with .type.{etc} as booleans rather than comparing strings. There's also the options for multiple things, I showed this off in the place of categories which are currently statically added to Channel

This is very conceptual, and there’s likely better ways of doing this, any edit, improvements, complete changes, or feedback that I’ll try my best to add in myself if you don’t feel like it are 300% accepted and appreciated.

**Status**
- [X] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [X] This PR changes the library's interface (methods or parameters added)
  - [X] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by jpbberry** [comment]
It failed due to the fact that I did not use a linter and I’m not home right now, take it for what it’s worth and if someone doesn’t fix it by the time I get home it’ll be fixed sorry.

**Comment by appellation** [comment]
This does not need a class. A simple string constant would achieve the same result with so much less complexity.

Also not a fan of delineating "special" channels since there is no such distinction in terms of the API.

**Comment by kyranet** [comment]
I agree with your PR that there should be a change regarding `Channel#type`, the current system is not future-proof, since we don't save the raw number from the API (which is inconsistent with some other structures) and we just assign `"unknown"` when the type is unsupported.

Sometimes Discord releases a new type of channel and we all have to upgrade so we can have this channel, though not ideal, as we can't use a workaround for it.

I think the correct way would be to implement `Channel#typeNumber` and `Channel#type` (getter that returns the current values), making an entire class just for this is overkill, though.

**Comment by appellation** [comment]
This is still unnecessarily complex. 👎

It's perfectly clear and idiomatic to do comparisons when checking for equality. `if (channel.type.text)` simply isn't as clear as `if (channel.type === ChannelTypes.TEXT)` or any variation thereof. I have never seen enums implemented in this way before and I can't say I like it.

👍 on @kyranet's comment, however I'm on the fence about having two properties for this. While having a lowercase string constant that people can just use in their comparisons (e.g. `if (channel.type === 'text')`) is certainly convenient but not necessarily a good design practice. Technically, we should do no string conversion and have people rely on predefined constants, but I'm not sure about the convenience tradeoff here.

**Comment by jpbberry** [comment]
Closing the PR. Thanks for all the feedback and while this obviously isn’t the best way of doing it, hopefully if anything came out of this, it’s that the channeltype system needs to be changed one way or another.

**Pull request closed without merging**
