### PR TITLE
feat(rest): use Agent with higher connect timeout

### LINKED ISSUE #8489: Random connection errors
### Which package is this bug report for?

discord.js

### Issue description

Random connection errors especially when using slash commands. I'm 100% sure my connection is strong enough. The error is given below:

```
ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (D:\Rakin\Projects\sudobot-v2\node_modules\undici\lib\core\connect.js:131:24)
    at D:\Rakin\Projects\sudobot-v2\node_modules\undici\lib\core\connect.js:78:46
    at Immediate._onImmediate (D:\Rakin\Projects\sudobot-v2\node_modules\undici\lib\core\connect.js:117:33)
    at processImmediate (node:internal/timers:464:21) {
  code: 'UND_ERR_CONNECT_TIMEOUT'
}
```

### Code sample

```typescript
// client = discord client
// this code might not always fail - for me the error was coming randomly

client.on('interactionCreate', async (interaction) => {
   if (interaction.isChatInputCommand()) {
      // do some stuff like bulk deleting messages or warning users

     await interaction.reply({ content: 'Done' });
   }
});
```

### Package version

v14.2.0

### Node.js version

v16.13.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildInvites, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent

### I have tested this issue on a development release

_No response_

### LINKED ISSUE #8629: Undici HeadersTimeoutError: Headers Timeout Error
### Which package is this bug report for?

rest v1.0.1

### Issue description

I get this error on large audio file uploads (50mb - 100mb)

```
HeadersTimeoutError: Headers Timeout Error
undici\lib\client.js:894:26
```

When I manually increase the headersTimeout in the undici client code to 60 seconds, it works, but the default value of 30s is too low and causes the issue. Is there anyway to specify a custom headersTimeout when initializing the discord client ?

### Package version

v14.3.0

### Node.js version

v17.0.1

### Operating system

Windows

### PR DESCRIPTION
**Pull request by KhafraDev**
**Please describe the changes this PR makes and why it should be merged:**

Fixes #8629 
Fixes #8489 

Repeated issue:
- https://discord.com/channels/222078108977594368/999007780524535978
- https://discord.com/channels/222078108977594368/1023364907619602522

I have no way of testing this but 30 seconds seems to work for others.

The issue seems to be with misconfigured ipv6, see https://github.com/nodejs/undici/issues/1531#issuecomment-1229889136

**Status and versioning classification:**

- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed) (Not really sure. Increases the time allowed to establish a connection.)

### CODE REVIEW

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Comment by virtual-designer** [comment]
Finally... have been waiting for a long time for this fix. Thanks @KhafraDev 👍🏻

**Comment by almostSouji** [comment]
This was merged under a minor release, but breaks the `get/getGlobalDispatcher` paradigm and probably needs to be reverted

**Comment by KhafraDev** [comment]
I was surprised it got merged so quickly, I even put that it was likely a breaking change. The real fix is probably waiting for https://github.com/nodejs/node/pull/44731 however.

**Comment by almostSouji** [comment]
After revisiting internally, we will likely not revert and monitor the repository for bugs caused by this. The chance of it being faulty is very unlikely. Overall the aforementioned pattern is questionable as a recommendation with the slightest consideration of our general user base, as it will globally alter undici for any requests, not just discord.js specific ones.

**Pull request merged**
