### PR TITLE
feat(User#locale)

### PR DESCRIPTION
**Pull request by iDroid27210**
**Please describe the changes this PR makes and why it should be merged:**

Cover the totally new Discord API feature: the user's locale. The locale set on the user's client (desktop/mobile) will be sent through the User object to bots.
**More information:** https://github.com/discordapp/discord-api-docs/issues/535

**Semantic versioning classification:**  
- [X] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by SpaceEEC** [comment]
This seems to be more of an oauth feature than a bot feature.

It is restricted to `GET /users/@me`, which limits it for bots to only themselves when one explicitly fetches them with `client.users.fetch('@me')`. (Not received via gateway)

Also bots seem to always have `en-US` as language.

**Comment by lloti** [comment]
Basically what space said.

This feature is adding support for a property which is _meant_ to be used with OAuth2 and since bots always have `en-US` (according to space) and this lib isn't looking to support user accounts (#2559) it wouldn't make much sense to have this property.

_But, feel free to change my mind._

**Comment by iDroid27210** [comment]
Eh you're right. There was a miscommunication on the original issue obviously. I thought bot accounts could get the locale, anyway.

To close :lock:

**Comment by devsnek** [comment]
can we re-open this? rpc uses it downstream

**Comment by iDroid27210** [comment]
:ok_hand:

**Pull request merged**
