### PR TITLE
refactor(Client): remove applicationCommand events

### PR DESCRIPTION
**Pull request by ImRodry**
**Please describe the changes this PR makes and why it should be merged:**
This PR removes applicationCommand events as a Discord developer said they were not meant to be sent to bots (https://github.com/discord/discord-api-docs/issues/3690#issuecomment-902915187). This can be a semver minor since the events never fired anyway.
Upstream PR: 
- https://github.com/discord/discord-api-docs/pull/3691

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Review by Jiralite — CHANGES_REQUESTED** [review]
You have missed these:
https://github.com/discordjs/discord.js/blob/e87324ed9d221ab7d13b8609f9a6fe1e72070707/src/util/Constants.js#L213-L215
https://github.com/discordjs/discord.js/blob/e87324ed9d221ab7d13b8609f9a6fe1e72070707/src/util/Constants.js#L267-L269
https://github.com/discordjs/discord.js/blob/e87324ed9d221ab7d13b8609f9a6fe1e72070707/typings/index.d.ts#L4684-L4686

**Review by vladfrangu — APPROVED** [review]
LGTM after Jiralite's comments are resolved

**Comment by ImRodry** [comment]
Sorry I fixed and forgot to push xD

**Review by SpaceEEC — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Comment by iCrawl** [comment]
This needs a rebase.

**Pull request merged**
