### PR TITLE
refactor(*): rewrite library

### PR DESCRIPTION
**Pull request by Shizuyokko**
**Please describe the changes this PR makes and why it should be merged:**
1. improved library performance 
2. minimal breaking changes
3. new features
4. voice support
5. well documentated https://abal.moe/Eris
6. passed tests
7. lightweight
8. really flexible
9. really up-to-date

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Comment by iCrawl** [comment]
I love it.

**Comment by Shizuyokko** [comment]
everything that you have listed will be released soon! https://github.com/abalabahaha/eris/pull/1216

**Comment by kyranet** [comment]
image

**Comment by san4ern** [comment]
🤔 
image
arnold swarcnigger??

**Comment by Lioness100** [comment]
As long as there's minimal breaking changes I'm all for this

**Comment by Ayfri** [comment]
`var`

**Comment by xHyroM** [comment]
> **Please describe the changes this PR makes and why it should be merged:**
> 
> 1. improved library performance
> 2. minimal breaking changes
> 3. new features
> 4. voice support
> 5. well documentated https://abal.moe/Eris
> 6. passed tests
> 7. lightweight
> 8. really flexible
> 9. really up-to-date
> 
> **Status and versioning classification:**
> 
> * I know how to update typings and have done so, or typings don't need updating
> * This PR changes the library's interface (methods or parameters added)
> * This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

lmao

**Comment by Gabe616** [comment]
I love this, why hasn't discord.js staff accepted this yet?

**Pull request closed without merging**
