### PR TITLE
refactor(guild)!: remove deprecated get guild overload

### PR DESCRIPTION
**Pull request by jaw0r3k**
**Please describe the changes this PR makes and why it should be merged:**
Removes the deprecated overload from getting a guild.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- **This PR includes breaking changes (methods removed or renamed, parameters moved or removed)**

### CODE REVIEW

**Review by kyranet — APPROVED** [review]

**Review by benjGam — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by didinele — CHANGES_REQUESTED** [review]
Pointless to block such a trivially backwards compatible change until the next major. We should just make overloads and deprecate the current one, IMO.

**Comment by jaw0r3k** [comment]
I guess we can, but do we want to put as much effort in it, especially that is is not that important 
Just wait for next major which probably is not going to be that far away from now

**Comment by didinele** [comment]
yes.

**Comment by Jiralite** [comment]
Opened #10143: a non-breaking pull request. This one may remain for the next major version.

**Review by suneettipirneni — APPROVED** [review]

**Review by didinele — APPROVED** [review]

**Review by benjGam — APPROVED** [review]

**Review by almeidx — APPROVED** [review]

**Pull request merged**
