### PR TITLE
[WIP] Add support for receiving video

### PR DESCRIPTION
**Pull request by amishshah**
**Please describe the changes this PR makes and why it should be merged:**
Discord now allows bots to receive video in voice channels where video is allowed. This PR will let developers create receive streams for video formats in addition to audio formats, e.g.:

```js
const videoFrameStream = receiver.createStream(user, { mode: 'VP8' }); // or VP9
```
Video support for bots has not been made official yet, however at the moment they can and I'm hoping this isn't changed. My implementation is based on observing what the Discord client does, so it may be slightly incorrect as there is no documentation for this as of yet.

## To do:
- Figure out a good method of interpreting the `speaking` property, which is now a bit field (see #2765)
  - At the moment, having a stream end on "silence" has been removed until the behaviour is decided for video streams
- Piece together payloads into VP8 frames
- Allow users to mux VP8 + Opus streams directly into a Webm stream using prism
- Achieve the same things for VP9, however VP8 is a priority -- I haven't encountered VP9 in use by the Discord client just yet
- Typings
- Documentation

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)in voice channels
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by ShayBox** [comment]
woo hydrabolt supports piracy 💃

**Comment by ShayBox** [comment]
I had a dream you merged this, I just had to check. Disappointing 😞

**Comment by amishshah** [comment]
Unfortunately, we won't be able to support video in the library:
image

**Comment by tyliec** [comment]
Tried cloning this PR and using it, does not work anymore 😢

**Comment by tyliec** [comment]
Scratch that, this seems to never have been finished. For those who come after, make sure you are using the VP8 codec by disabling H264 in your Voice & Video settings.

**Pull request closed without merging**
