### PR TITLE
types(*): make hex color types compatible with ColorResolvable

### PR DESCRIPTION
**Pull request by ImRodry**
**Please describe the changes this PR makes and why it should be merged:**
In #5950 the type for ColorResolvable was changed from `string` to `#${string}`. This meant that assigning a hexColor from the library to a ColorResolvable parameter would error out, so this PR fixes that.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by ImRodry** [comment]
I also thought of creating a HexColor type so it can be used and found more easily in the future, will probably add this tomorrow if you’re okay with that

**Review by kyranet — APPROVED** [review]

**Comment by kyranet** [comment]
Yeah, sure, `HexColorString` (or `HexadecimalColorString`) sounds good to me.

**Review by iCrawl — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Comment by ImRodry** [comment]
All good to go now

**Comment by iCrawl** [comment]
Can we put it where the other utility types are, and not awkwardly between 2 classes that use it?

**Comment by ImRodry** [comment]
Oh I just sorted it alphabetically, sure

**Pull request merged**
