### PR TITLE
docs(RoleManager): everyone role can't be null

### PR DESCRIPTION
**Pull request by HarmoGlace**
**Please describe the changes this PR makes and why it should be merged:**
This PR fixes the jsdoc of RoleManager ; the everyone role can't be null

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by NotSugden** [comment]
this should be for the master branch and not the stable branch - also the typings should be updated for this too

**Comment by kyranet** [comment]
It can be null, I could very well do `guild.roles.cache.delete(guild.id);`, and that method would return undefined.

Because the possibility exists, this getter should return null if not present.

**Comment by HarmoGlace** [comment]
You are right, but if you do that, everything can be nullable, including the highest role of the guild who's not nullable in the jsdoc

**Comment by RDambrosio016** [comment]
> It can be null, I could very well do `guild.roles.cache.delete(guild.id);`, and that method would return undefined.
> 
> Because the possibility exists, this getter should return null if not present.

I disagree with the premise of marking it null based on the fact that the user could simply manually delete it, if we are accounting for that, then there are boatloads of changes that need to be done. These types of methods should assume the user has not touched cache, which is usually safe to assume.

**Pull request merged**
