### PR TITLE
refactor(invite): make `channel` and `inviter` getters

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**
https://github.com/discordjs/discord.js/pull/7089#discussion_r767199403

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Review by Jiralite — CHANGES_REQUESTED** [review]
Per https://discord.com/developers/docs/resources/invite#invite-object, `Invite#channel` is nullable. Please address this!

**Comment by almeidx** [comment]
@Jiralite would that make the `channelId` property nullable? I'm not sure where this [`channel_id` property](https://github.com/discordjs/discord.js/pull/7278/files#diff-1a87f7fb00fc0993891ebe48a7b1b7261d976e79b7c42622a542e9045463f314R155-R161) in the data is coming from

**Comment by ImRodry** [comment]
> @Jiralite would that make the `channelId` property nullable? I'm not sure where this [`channel_id` property](https://github.com/discordjs/discord.js/pull/7278/files#diff-1a87f7fb00fc0993891ebe48a7b1b7261d976e79b7c42622a542e9045463f314R159-R161) in the data is coming from

There... is no channel_id property?

**Comment by Jiralite** [comment]
`channelId` would be nullable, yes.

I have an issue with this refactor... When we receive the inviter object, only the id is extracted. `Invite#user` will be `null` if we do not have them cached _before_ despite that user data already being sent to us.

**Comment by Jiralite** [comment]
> > @Jiralite would that make the `channelId` property nullable? I'm not sure where this [`channel_id` property](https://github.com/discordjs/discord.js/pull/7278/files#diff-1a87f7fb00fc0993891ebe48a7b1b7261d976e79b7c42622a542e9045463f314R159-R161) in the data is coming from
> 
> There... is no channel_id property?

There is as documented from audit logs.

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Pull request merged**
