### PR TITLE
chore: remove -types import in readme example

### PR DESCRIPTION
**Pull request by BaumianerNiklas**
**Please describe the changes this PR makes and why it should be merged:**
As of #7909 discord.js re-exports everything from discord-api-types, so there's no need in installing it as a redundant dependency. 

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.
- Code changes have been tested against the Discord API, or there are no code changes

### CODE REVIEW

**Review by vvito7 — COMMENTED** [review]
There is also this one:
https://github.com/discordjs/discord.js/blob/96053babe1bd65ebe1fc6a261f5eb052906afdb9/packages/discord.js/README.md?plain=1#L47-L51

**Comment by ImRodry** [comment]
/rest comes installed with djs so you can also remove that

**Comment by Syjalo** [comment]
> /rest comes installed with djs so you can also remove that

Only the error. Not the `REST` class.
image

**Comment by ImRodry** [comment]
It still comes installed so you don’t have to install it

**Comment by Syjalo** [comment]
> It still comes installed so you don’t have to install it

If you use a package in your code you should install it as a dependency.

**Comment by ImRodry** [comment]
Debatable because if you install a more recent version than the one djs has installed it might cause conflicts

**Comment by didinele** [comment]
👎 Using a package you haven't explicitly installed is one of the worst practices, please don't tell people to do this. The ideal solution would be to change the command to like, `discord-api-types@^0.33.5` (assuming current d.js is on 0.35) and keep it up to date.

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
