### PR TITLE
Remove Guild#member

### LINKED ISSUE #4888: Remove Guild#member
**Is your feature request related to a problem? Please describe.**
The `Guild#member` method is a poorly-named helper method for `Guild#members#cache#get`.

**Describe the ideal solution**
The method should either be removed entirely in the next major version of the library as an extraneous helper method, or it should be renamed appropriately if kept.  Method naming conventions usually involve verbs, which this method does not include.

### PR DESCRIPTION
**Pull request by anandre**
Remove `Guild#member` as it's a poorly-named helper method for `Guild#members#resolve` (although not a 1-to-1, I do understand).

Fixes #4888

**Status**

- [X] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [X] This PR changes the library's interface (methods or parameters added)
  - [X] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Vaporox** [comment]
These lines need to be changed to use `Guild#members#resolve` too:
<details>
<summary><b>Click to expand</b></summary>

https://github.com/discordjs/discord.js/blob/367013c12088b4b3071c5accf69f424b7fa17b4a/docs/examples/moderation.md#L36
https://github.com/discordjs/discord.js/blob/367013c12088b4b3071c5accf69f424b7fa17b4a/docs/examples/moderation.md#L108
https://github.com/discordjs/discord.js/blob/367013c12088b4b3071c5accf69f424b7fa17b4a/src/client/voice/VoiceConnection.js#L504
https://github.com/discordjs/discord.js/blob/367013c12088b4b3071c5accf69f424b7fa17b4a/src/client/voice/VoiceConnection.js#L504
https://github.com/discordjs/discord.js/blob/367013c12088b4b3071c5accf69f424b7fa17b4a/src/structures/Message.js#L280
https://github.com/discordjs/discord.js/blob/367013c12088b4b3071c5accf69f424b7fa17b4a/src/structures/MessageMentions.js#L141
https://github.com/discordjs/discord.js/blob/367013c12088b4b3071c5accf69f424b7fa17b4a/src/structures/Role.js#L130
https://github.com/discordjs/discord.js/blob/367013c12088b4b3071c5accf69f424b7fa17b4a/test/random.js#L119
</details>

**Comment by anandre** [comment]
Believe I got all of the needed changes.  Really wondering about that code in the random.js file, it seems really unwieldy, but I left it for now since it's not really in the scope of this PR.

**Comment by monbrey** [comment]
You should note that this closes #4888

**Review by vladfrangu — APPROVED** [review]
Provided all uses of `member(` have been replaced in the code, LGTM

**Review by iCrawl — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Pull request merged**
