### PR TITLE
feat(LimitedCollection): export LimitedCollection

### LINKED ISSUE #4274: LimitedCollection
**Is your feature request related to a problem? Please describe.**
There are scenarios where I would actually want to use the Limited Collection class, but you cannot import the LimitedCollection class from discord.js, unless you do something like the following: 
```js
const LimitedCollection = require(require.resolve("discord.js").replace("index.js", "util/LimitedCollection.js"))
```
In the discord.js docs, it's listed as Private, but it says that you can initiate the class with 
```js
new Discord.LimitedCollection(maxSize, iterable);
``` 
but this isn't true as its not in the `src/index.js` file and doesn't get imported when you require the library.

**Describe the ideal solution**
I suppose it would make sense to simply add it to the `src/index.js` file, or even add it in the `@discordjs/collection` package in some way.

I guess it would be easy to recreate it or just use the alternative way of getting the class but it'd be so much more simple if it was added to the index file and/or made public.

### PR DESCRIPTION
**Pull request by PanSzelescik**
**Please describe the changes this PR makes and why it should be merged:**

Closes #4274, I don't know why it isn't exported

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Comment by ckohen** [comment]
Please remove the @private docstring in the file

**Comment by PanSzelescik** [comment]
> Please remove the `@private` docstring in the file

Removed

**Review by iCrawl — APPROVED** [review]

**Comment by PanSzelescik** [comment]
Should I add typings in [Collections region](https://github.com/discordjs/discord.js/blob/fe5d56c9b11b3e5f05933c6d746237b9f353b392/typings/index.d.ts#L2295)?

**Review by SpaceEEC — APPROVED** [review]
There is still the issue with implicitly creating new instances of `LimitedCollection` through its methods, e.g. `clone`, `filter`.
TS will say those are `LimitedCollection`s, but they actually are `Collections`.
(Creating new `LimitedCollection`s is not possible without modifying `Collection` and thinking of a way to derive new arbitrary child instances)

I don't know of a way to make TS aware of `Symbol.species` and overwriting all methods to specify that actually a `Collection` is returned is error prone and tedious.

So I suppose 🤷

**Comment by SpaceEEC** [comment]
Yeah, moving the declaration for `LimitedCollection` would be nice, @PanSzelescik.

**Comment by iCrawl** [comment]
This needs a rebase.

**Pull request merged**
