### PR TITLE
fix(example-readme): use yarn instead of npm for main repo

### PR DESCRIPTION
**Pull request by ReFruity**
**Please describe the changes this PR makes and why it should be merged:**
Old readme in examples uses npm for the main repo, should be yarn instead

### CODE REVIEW

**Comment by ReFruity** [comment]
We can also get rid of `file:../../` and replace it with stable version of the library.
My argument was:
> I don't think using the main repo is a good idea. Developers often just copy-paste code. They will use the released version in their code therefore it's best for an example to use release.

**Comment by lewis45454** [comment]
I would recommend documenting npm and yarn.

You could documentate it like:

**NPM**
npm install
npm run build

**Yarn**
yarn --immutable
yarn build

**Comment by ReFruity** [comment]
@ImRodry "Contributing" [section](https://github.com/discordjs/discord.js/blob/358c3f4a46638fc818e65fcc113d84818bb68c10/.github/CONTRIBUTING.md#setup) provides only yarn code. I tried using npm first too, because I am used to it, but install command quickly failed.

**Comment by didinele** [comment]
> I think the readme should display solutions using the tool that is builtin with node - npm

As of Node 14.19.0 and 16.9.0, both `yarn` and `pnpm` are easily available "builtin with node" thanks to corepack.

**Comment by ImRodry** [comment]
corepack is opt-in and I had never even heard of it before, I assume your average d.js user hasn’t either

**Review by lewis45454 — CHANGES_REQUESTED** [review]
Use npm and yarn

**Comment by ReFruity** [comment]
> Use npm and yarn

`npm install` fails in the main repo for me:
```
➜  discordjs git:(main) npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tony/.npm/_logs/2022-06-24T17_27_14_664Z-debug-0.log
```

**Comment by lewis45454** [comment]
> > Use npm and yarn
> 
> `npm install` fails in the main repo for me:
> 
> ```
> ➜  discordjs git:(main) npm install
> npm ERR! code EUNSUPPORTEDPROTOCOL
> npm ERR! Unsupported URL Type "workspace:": workspace:^
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/tony/.npm/_logs/2022-06-24T17_27_14_664Z-debug-0.log
> ```

If yarn works then this PR is fine.

**Comment by ReFruity** [comment]
> If yarn works then this PR is fine.
Yes, yarn works fine in the main repo

**Comment by iCrawl** [comment]
I already posted this in https://github.com/discordjs/discord.js/pull/8123 but will quote it here again to have it on record:

> Our plan is to put the voice examples in a different repository [...]

So I think we should be fine not going forward with this change for now, keep the other PR and then slowly move over to the new repo.

**Pull request closed without merging**
