### PR TITLE
feat(ApplicationCommandOptionType): add NUMBER (10)

### PR DESCRIPTION
**Pull request by advaith1**
**Please describe the changes this PR makes and why it should be merged:**
- https://github.com/discord/discord-api-docs/pull/3455

Since this is currently only implemented in the canary API, you must add `http: {headers: {'x-debug-options': 'canary'}}` or `http: {api: 'https://canary.discord.com/api'}` to your ClientOptions to create type 10 options. They can also currently only be viewed on the canary client.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by monbrey** [comment]
What exactly is this, support for floating point vs the INTEGER option type?

**Comment by iCrawl** [comment]
Yes

**Comment by advaith1** [comment]
yeah

**Review by joseywoermann — APPROVED** [review]

**Comment by Abdualml** [comment]
Y

**Review by vladfrangu — APPROVED** [review]
If that's all we have to do, :woah: 
LGTM

**Comment by advaith1** [comment]
> If that's all we have to do, :woah:

this was made before OptionResolver got merged, I'll add that but then it should be all

**Review by iCrawl — APPROVED** [review]

**Comment by iCrawl** [comment]
🚀 https://github.com/discord/discord-api-docs/pull/3455

**Review by kyranet — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Pull request merged**
