### PR TITLE
New permissions added

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by iCrawl** [comment]
We don't accept PRs to stable.

**Comment by Justman10000** [comment]
> 
> 
> We don't accept PRs to stable.

And where else do you put it?

**Comment by vanishedvan** [comment]
> > We don't accept PRs to stable.
> 
> And where else do you put it?

To the master branch.

**Comment by Justman10000** [comment]
> 
> 
> > > We don't accept PRs to stable.
> > 
> > 
> > And where else do you put it?
> 
> To the master branch.

The master branch receives more than the stable! But why is it called master? Shouldn't it be called beta or something?

**Comment by monbrey** [comment]
master is where changes are made and tested. Stable is not changed by PRs, ever, else it wouldn't be "stable".

When a collection of changes are completed, tested and considered ready for release, the master branch becomes the new stable.

The current stable release is v12.5.3, the next will be 13.0.0.

**Pull request closed without merging**
