### PR TITLE
fix(BaseMessageComponent): don't create new class instances

### LINKED ISSUE #7139: Components passed into action row are not the same as the components that are used in action row creation
### Issue description

Whenever I pass in a component to an action row, the original component ceases to manipulate the action row.

### Code sample

```typescript
const button = new MessageButton()
    .setCustomId("discard")
    .setStyle("DANGER")
    .setEmoji("922315496559349800");
const row = new MessageActionRow().addComponents(button);
button.setDisabled(true);
console.log(row.components[0].disabled) // Should be true, is false
```

### discord.js version

13.3.1

### Node.js version

17.2.0

### Operating system

MacOS

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

CHANNEL

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, DIRECT_MESSAGES

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by ImRodry**
**Please describe the changes this PR makes and why it should be merged:**
Feel free to give the PR a better title as I didn't know what to call this but this basically resolves #7139 by returning the component instance in BaseMessageComponent#create when the received data is already a discord.js class

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by suneettipirneni** [comment]
Just out of curiosity whats the performance difference here? Kinda interested to see if this has a performance upgrade

**Comment by ImRodry** [comment]
I tested it with an example class and it seems to be quite significant, not sure if this test is 100% accurate though
image

**Review by nitinkumar-c — APPROVED** [review]
Working 100%

**Comment by vladfrangu** [comment]
> RE https://github.com/discordjs/discord.js/pull/7140#issuecomment-999966060

if you want an accurate performance, you'd have the class and main component creation as a setup, not in the test case. Just as an fyi 😄

---

Leaving that aside, this PR looks fine to me, but I'll let the rest of the maintainers decide if we merge this :D

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
