### PR TITLE
feat(cli): improve CLI functionality

### PR DESCRIPTION
**Pull request by malezjaa**
### **Description:**

Hey!

This pull request aims to enhance the project configuration process and make it more user-friendly and enjoyable.

### **Changes Made:**

- Implemented a guided prompt system using the `@clack/prompts` library to provide users with a smoother and more intuitive project setup experience.
- Improved the style of messages displayed during the project configuration.

### **Testing:**

Manually tested the project setup process, ensuring that the prompts function correctly and the generated project structure is accurate.

### **Reason:**
This pull request aims to improve the project configuration process by introducing a guided prompt system and enhancing the message style. It simplifies the setup experience, making it more user-friendly and enjoyable. Your review would be appreciated.

image

### CODE REVIEW

**Comment by Jiralite** [comment]
Have you seen #9570?

**Comment by malezjaa** [comment]
Oh. xd

**Comment by malezjaa** [comment]
Why couldn't this have been merged earlier?

**Comment by Jiralite** [comment]
It is not merged/

**Comment by malezjaa** [comment]
Pardon me, I meant, why wasn't this merged at all?

**Pull request closed without merging**
