### PR TITLE
feat(Message): add url getter

### PR DESCRIPTION
**Pull request by Lewdcario**
**Please describe the changes this PR makes and why it should be merged:**
Not much to say- adds the brand spanking new feature of jumping to messages.

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by iCrawl** [comment]
-1 on this for me.

**Comment by bdistin** [comment]
Quote commands, Highlight bots, I could see even someone enhancing tag commands by giving an option to go back to when and where the tag was created.

Will everyone use it? Absolutely not. But that's exactly the same for every other feature in this library. There are far less useful things in the library.

**Comment by iDroid27210** [comment]
You are right, but this is just a string that we can build ourselves.
If Discord decides to edit this feature (changing the endpoint, or something else) we would have to make a pull request (**to change a single string**) and bot developers who are using it would have to wait until the next version of d.js is released.

**Comment by bdistin** [comment]
You can build your own avatar strings too, why do we need a method to build strings we can build our selves... /s

**Comment by lloti** [comment]
"But this is just a string we could build ourselves" pssh, have you seen like, every getter, ever?

**Comment by lloti** [comment]
Also, cause I'm already here, as I mentioned yesterday to @Lewdcario in Discord, I believe this getter should just be called `url` but don't know what everyone else thinks, so feel free to vote on this comment.

**Comment by kyranet** [comment]
+1 on renaming it to `url`, since the `jumpTo` qs parameter has been removed.

**Pull request merged**
