### PR TITLE
fix(BitField): use only enum names in iterating

### PR DESCRIPTION
**Pull request by jaw0r3k**
**Please describe the changes this PR makes and why it should be merged:**
Backports to v13:
- #9357 

**Status and versioning classification:**
- Typings don't need updating
- This PR only includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by vladfrangu** [comment]
Just curious, does this version even have the same bug? 👁️

**Comment by Jiralite** [comment]
Probably? https://github.com/discordjs/discord.js/pull/9271/commits/630d4f33cd1a18a10b371233fe74a081da9f2d8e

**Review by SpaceEEC — CHANGES_REQUESTED** [review]
I'm unable to see anything to fix here, we don't seem to use any TS-enums in v13. 😅 
(Otherwise this would probably need to be applied to `serialize` too.)

**Comment by jaw0r3k** [comment]
Well you are right, v13 uses only pure objects

**Pull request closed without merging**
