### PR TITLE
[feat]: Addition of Collector#resetTimer()

### PR DESCRIPTION
**Pull request by matthewfripp**
**Please describe the changes this PR makes and why it should be merged:**
To achieve this before you had to not pass a time option, and utilise setTimout()/clearTimeout() instead.
This PR provides an easy alternative

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Monbrey** [comment]
Good idea to add this method.

What about having this or another method accept an optional parameter to change the timer?

**Comment by matthewfripp** [comment]
Not sure whether to create two separate methods for the normal and idle timeout, or just make resetTimer() take the optional parameter and change both at once?

**Comment by adrifcastr** [comment]
pls merge

**Comment by Monbrey** [comment]
This could be updated to use [Timeout.refresh()](https://nodejs.org/api/timers.html#timers_timeout_refresh) since master has a minimum Node version 10.2 which would support this.

> Not sure whether to create two separate methods for changing the normal and idle timeout, or just make resetTimer() take the optional parameter and change both at once?

I'd suggest having resetTimer (or changeTimer if separate method) accept a similar options object to the initial creation, so people specify which one/both they're changing eg `collector.resetTimer({ time: 60000, idle: 20000 })`

This wouldn't be achievable with `Timeout.refresh()` however.

**Comment by iCrawl** [comment]
#3825

**Pull request closed without merging**
