### PR TITLE
refactor: change const enums to interfaces

### PR DESCRIPTION
**Pull request by DTrombett**
**Please describe the changes this PR makes and why it should be merged:**

This PR converts all `const enum`s to `interface`s and move them to the main `index.d.ts` file so that TS users can use index access with variables without receiving the error `A const enum member can only be accessed using a string literal`.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by SpaceEEC — CHANGES_REQUESTED** [review]
Doing this brings back this issue: https://github.com/discordjs/discord.js/pull/6065#discussion_r664458288

Those enums should either be objects in the declarations or enum equivalents in the constants file (would require a small modification to the `createEnum` function)

**Comment by DTrombett** [comment]
Mmh should we change them to interfaces or types?

**Comment by vladfrangu** [comment]
If we go with space's suggestion, I'm more leaning towards the latter

**Comment by SpaceEEC** [comment]
I think we'd use interfaces there, if we go that route.

**Comment by DTrombett** [comment]
So I should move them to the main index.d.ts file and convert them to interfaces?

**Comment by DTrombett** [comment]
Converted all const enums to interfaces. LMK if it's ok.

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by kyranet — APPROVED** [review]
A very large downside of this is that we can't use them like enums anymore in types, which forces us to do `typeof ConstantsEvents['MESSAGE_CREATE']` over `ConstantsEvents.MESSAGE_CREATE`, but sure.

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
