### PR TITLE
Mark peer dependencies as optional

### PR DESCRIPTION
**Pull request by ccope**
**Please describe the changes this PR makes and why it should be merged:**
Mark peer dependencies as optional to quiet warnings from yarn.
This structure was approved as https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md
Support was released in Yarn 1.13.

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by amishshah** [comment]
What about npm?

**Comment by ccope** [comment]
Looks like npm doesn't support the feature: https://github.com/npm/npm/issues/3066
But I'll verify that this doesn't break it tomorrow.

**Comment by ccope** [comment]
Confirmed that npm still works with the additional metadata, it just ignores it.

**Comment by PyroTechniac** [comment]
Doesn't npm support an optionalDependencies field in package.json?

**Comment by xDimGG** [comment]
Yes, it does, and discord.js avoids using it as it is opt-out unlike peerDependencies which is opt-in (both via cli flags).

**Comment by ccope** [comment]
Prior discussion about optionalDependencies in #1222 and #1215
It appears that NPM is aware of discord.js's problem as well: https://github.com/yarnpkg/rfcs/pull/105#issuecomment-440371169

**Pull request merged**
