### PR TITLE
refactor(Managers): rename add to _add

### PR DESCRIPTION
**Pull request by 1Computer1**
**Please describe the changes this PR makes and why it should be merged:**

Cus names conflict. Have fun reviewing. It's still a mess.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Comment by ImRodry** [comment]
While you're at it, why not rename patch to _patch?

**Comment by 1Computer1** [comment]
Someone else can do that.

**Comment by iCrawl** [comment]
Didn't you also say that for this PR.

**Comment by 1Computer1** [comment]
💢

**Comment by vladfrangu** [comment]
> While you're at it, why not rename patch to _patch? Or maybe even rename all private properties and methods to add a _ at the beginning

If you're talking about Message#patch, it'd need a proper rename, since it's the function called from MESSAGE_UPDATE 👀, something like `_messageUpdatePatch` or such

**Comment by ImRodry** [comment]
Hm I’m not sure that’d be necessary since there are other _patch functions in other classes, would just be for the sake of consistency and doesn’t need such a big name

**Comment by ckohen** [comment]
Message also already has a _patch

**Comment by iShibi** [comment]
```ts
export interface ThreadMemberManager
extends Omit<CachedManager<Snowflake, ThreadMember, ThreadMemberResolvable>, 'add'> {}
```
In the typings, the `CachedManager` class doesn't have the `add` method anymore, thus there is no need to omit it [here](https://github.com/discordjs/discord.js/blob/7cdf63352a7801de4cfb11bad2f5340c0c71e72c/typings/index.d.ts#L2496) for creating the `ThreadMemberManager` interface. That line can be removed completely and the `ThreadMemberManager` class can extend it just like the others.

*Bonus: no lack of new line will be felt, if there is no line to add a new line after* 😼

**Comment by iCrawl** [comment]
This needs a rebase.

**Review by iCrawl — APPROVED** [review]

**Comment by ckohen** [comment]
Since this PR is touching it, `ThreadMemberManager#_add` can be cleaned up a bit (should've done it better to begin with, sorry). Basically remove everything inside it and replace with `return super._add(data, cache, { id: data.user_id });`. If that feels out of scope, I'll do it in another PR.

**Comment by kyranet** [comment]
It's better to do another PR for it, @ckohen

**Review by SpaceEEC — DISMISSED** [review]
You missed one instance :eyes:
https://github.com/discordjs/discord.js/blob/755c180659c125532fe6f8e33e6c3b56e275311b/src/managers/GuildChannelManager.js#L172

**Review by vladfrangu — APPROVED** [review]
Noice

**Review by SpaceEEC — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Pull request merged**
