### PR TITLE
Convert .login token parameter to an object

### PR DESCRIPTION
**Pull request by lewis45454**
**Please describe the changes this PR makes and why it should be merged:**
This PR converts the .login function token parameter to an object.

**Status and versioning classification:**
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by kyranet** [comment]
What's the reasoning behind this? There are no more options for `Client.login`, nor we plan to make everything that takes one parameter be an object.

**Comment by kyranet** [comment]
By that logic, we should make everything take an object, but no, it does not make code more readable.

If you want to make your usage more readable, you can try something like:

```javascript
import { token } from './config.js';

await client.login(token);
```

Or if you use `.env`, you can just define the `DISCORD_TOKEN` variable, and do the following:

```javascript
await client.login();
```

As it's what the token defaults to:

https://github.com/discordjs/discord.js/blob/e24970e3c3d24f71ba711e59666cd8a49a33e33b/packages/discord.js/src/client/Client.js#L143-L150

**Comment by lewis45454** [comment]
Would it be better if I changed "my token" to "bot token" for the jsdoc and revert the object back to a single value?

**Comment by kyranet** [comment]
Furthermore, Visual Studio Code has this option: `javascript.inlayHints.parameterNames.enabled`

When enabled, it will show the name of the argument, as shown below:

image

---

About your question, I really have no preference, we use [`#library-discussion`](https://canary.discord.com/channels/222078108977594368/682166281826598932) in [discord.js](https://discord.gg/djs) to discuss changes in the library.

**Pull request closed without merging**
