### PR TITLE
feat(components): Add unsafe message component builders

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

This adds new builders that don't perform any validation on input:
- `UnsafeButtonComponent`
- `UnsafeSelectMenuComponent`
- `UnsafeSelectMenuOption`
- `UnsafeEmbed`

If you'd like to use a shorter name I'd recommend renaming the imports for your needs:

```ts
import { UnsafeButtonComponent as ButtonComponent } from `@discordjs/builders`;

// Optional - Reexport them from a file to avoid repeating this process
export { ButtonComponent };
```

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by ImRodry** [comment]
Can't this be an option on the original builders and not a new class?

**Comment by suneettipirneni** [comment]
> Can't this be an option on the original builders and not a new class?

We discussed this internally, we would rather have a separate class than have an if branch for all methods on one class.

**Comment by vitorlops** [comment]
Isn't it supposed to have the types for each parameter in `UnsafeSelectMenu.ts`, `UnsafeSelectMenuOption.ts` and `UnsafeEmbed.ts` files?

**Comment by imranbarbhuiya** [comment]
> Isn't it supposed to have the types for each parameter in `UnsafeSelectMenu.ts`, `UnsafeSelectMenuOption.ts` and `UnsafeEmbed.ts` files?

They are coming from ts file which'll auto generate types.

**Comment by vitorlops** [comment]
Got it, thanks for explaining.

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by imranbarbhuiya — COMMENTED** [review]
Types also

**Review by iCrawl — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Comment by iCrawl** [comment]
This needs a rebase.

**Pull request merged**
