### PR TITLE
test(disableMention): use switch statement for commands

### PR DESCRIPTION
**Pull request by pizzafox**
**Please describe the changes this PR makes and why it should be merged:**

Massively increase performance of the disasbleMention test file.
This is good and also very necessary.

**Status**

- [ ] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by pizzafox** [comment]
Why are you reacting with 😕 this is an important PR

**Comment by tipakA** [comment]
Please leave the shitposts out of the repositories. Hactoberfest ended over a week ago, and there is no major difference between switch and if/else if,

**Comment by pizzafox** [comment]
I am well aware Hacktoberfest is over. This change could influence developers who are still learning to use `switch` statements which perform better and are great for solving problems like these.

**Comment by kyranet** [comment]
It's an "informal" test file made quickly to test stuff, nothing that needs to fancy, and definitely not something users read.

Besides, users should use a proper command handler or a framework, not a large switch case.

**Comment by pizzafox** [comment]
devsnek: switch statements can't be O(1) unless the entire domain of values is covered
but either way I would merge that, it's more readable

**Comment by kyranet** [comment]
Readability is subjective. Don't get me wrong, I use `switch`, but I do so very rarely (normally inside helper functions that always `return`). By itself, `switch` comes with a few readability drawbacks:

- It uses a lot of keywords (`switch`, `case:`, `break`/`return`).
- It has a lot of grammar going on, lint rules require braces to be opened (`case: { ... }`) when at least one assignment is made, this creates certain inconsistency and makes the `break;` feel out of place.
- Limitations and even hard-to-predict behaviour inside loops - does a `continue;` or a `break;` inside a loop affect the `switch`, or does it affect the loop itself? How do I enter and exit from a switch in a non-`default` case inside a loop and have it run the code below?
- It increases indentation and makes the code bulkier as it gets very expanded.

And as devsnek said, it's not `O(1)` unless all cases are covered. It is not in this case, therefore it's `O(n)` (where `n` is the amount of cases), sharing the same costs as regular `if` and `if else` chains. Therefore, there's no performance improvement here. And if there is, it'll be noticeable after hundreds of millions of iterations.

**Comment by monbrey** [comment]
`disableMentions` is a candidate for removal anyway, as Discord's `allowed_mentions` API parameter supersedes it in pretty much every way.

**Pull request closed without merging**
