### PR TITLE
chore: make `@types/node-fetch` a regular dependency

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

We use `node-fetch` types within the public rest API definitions so it should be a non-dev dependency.

**Status and versioning classification:**:
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Comment by ImRodry** [comment]
@discordjs/rest does use node-fetch types but none of these are exported by discord.js nor used as types in the typings file, are they?

**Comment by vladfrangu** [comment]
Consider generated definition files, which cause issues in your project if you try to compile a TS project without them 🙂 
It's also why we have @types/ws in discord.js

**Comment by ImRodry** [comment]
> Consider generated definition files, which cause issues in your project if you try to compile a TS project without them 🙂 It's also why we have @types/ws in discord.js

Well `@types/ws` is imported in the typings file whereas `node-fetch` isn't. Furthermore none of the imported or exported types rely on types coming from `node-fetch`, which is why I was asking
https://github.com/discordjs/discord.js/blob/355f579771771a28a293c327a38574c8918d18f8/packages/discord.js/typings/index.d.ts#L87

**Comment by almeidx** [comment]
The change was done in /rest and not discord.js

**Review by SpaceEEC — APPROVED** [review]

**Comment by oceanroleplay** [comment]
@iCrawl A patch release is needed for this, as builds fail for the development version.
image

however, confirm this at your end.

**Comment by ImRodry** [comment]
/rest was added in v14 so all you need is the latest dev release

**Comment by oceanroleplay** [comment]
> /rest was added in v14 so all you need is the latest dev release

Thank you but I am very well aware about that, I am using `^14.0.0-dev.1643674011.803665`

**Pull request merged**
