### PR TITLE
types: return `ReadonlyCollection`s where applicable

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

Return readonly collections in areas where we return data based on the API.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by kyranet — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by SpaceEEC — CHANGES_REQUESTED** [review]
How do you define "applicable"?

For example `BaseGuildTextChannel#fetchWebhooks` returns a `ReadonlyCollection`, while `BaseGuildTextChannel#fetchInvites` returns a regular `Collection`.

**Comment by suneettipirneni** [comment]
> How do you define "applicable"?
> 
> 
> 
> For example `BaseGuildTextChannel#fetchWebhooks` returns a `ReadonlyCollection`, while `BaseGuildTextChannel#fetchInvites` returns a regular `Collection`.

Looks like blab oversight.

**Comment by almeidx** [comment]
`ReadonlyCollection` should be exported in the typings too

**Review by SpaceEEC — CHANGES_REQUESTED** [review]
There are still quite a few `Collection`s being returned where I'd expect a `ReadonlyCollection` (if I understand this PR correctly).
Most notable all the `fetch*` methods, but also `GuildAuditLogs`' properties as well as `*Collector`'s callbacks.

But it feels like most references of `Collection` in there should be `ReadonlyCollection`s.

**Pull request closed without merging**
