### PR TITLE
feat: add channel banner feature

### PR DESCRIPTION
**Pull request by iShibi**
**Please describe the changes this PR makes and why it should be merged:**

- discord/discord-api-docs#4068

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by ImRodry** [comment]
bannerURL() perhaps?

**Comment by iShibi** [comment]
> bannerURL() perhaps?

when it gets documented

**Comment by ImRodry** [comment]
Endpoint is /channels/:channel/banners/:banner.jpg

**Review by thebigwolfy — APPROVED** [review]

**Review by thebigwolfy — APPROVED** [review]

**Comment by SpaceEEC** [comment]
Closing due to the upstream PR being closed:

> As this feature never shipped, we have no reason to document it.

https://github.com/discord/discord-api-docs/pull/4068#issuecomment-1082107550

**Comment by almostSouji** [comment]
Feature discontinued upstream

**Pull request closed without merging**
