### PR TITLE
docs: remove unused `Locale` typedef

### PR DESCRIPTION
**Pull request by N1ckPro**
**Please describe the changes this PR makes and why it should be merged:**
Removes the unused typedef, as requested in the reviews

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Jiralite** [comment]
Shouldn't this be removed @Qjuh?

**Comment by Qjuh** [comment]
Why should that be removed? As long as mainlib discord.js is JavaScript it should have JSDoc for intellisense purposes of non-ts users.

**Comment by Qjuh** [comment]
Oh wait, now I see. Yes, that should be removed, because we reference the external `discord-api-types/v10` Locale in https://github.com/discordjs/discord.js/blob/a1a3a95c94194a8ab789d567a778b376e13ea973/packages/discord.js/src/util/APITypes.js#L414 for documentation purposes. My bad

**Review by kyranet — APPROVED** [review]

**Review by kyranet — CHANGES_REQUESTED** [review]
Sorry, I didn't read the conversation first. Yes, the list should be removed, the typedef is already defined and links to discord-api-types's docs which is up-to-date.

**Comment by N1ckPro** [comment]
I've updated the PR to remove the typedef instead as you suggested

**Review by Jiralite — APPROVED** [review]

**Review by almeidx — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Pull request merged**
