### PR TITLE
feat: improve ts support

### PR DESCRIPTION
**Pull request by OmgImAlexis**
**Please describe the changes this PR makes and why it should be merged:**

This drastically improves the usability of this library while using IntelliSense. From here on out all changes to types should be done in the `src` directory. The old `typings` directory should serve as a rough reference.

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by monbrey** [comment]
This is not a TypeScript library.
The TypeScript rewrite of discord.js is a brand new project: <https://github.com/discordjs/discord.js-next/>

**Comment by OmgImAlexis** [comment]
@monbrey this is a few hours work at best and it honestly seems more complete than the one you linked..

**Comment by vBread** [comment]
> this is a few hours work at best 
No one asked you to do this. 

> and it honestly seems more complete than the one you linked..
Because it's still in development.

> This also works right now as a drop in replacement so I'm not 100% sure what the issue is.
You don't see an issue with switching the lib to TS?

**Comment by OmgImAlexis** [comment]
> No one asked you to do this.

Working to open source. 👋 

> Because it's still in development.

"In development"... yeah there are PRs left in an almost empty state and it's been that way for months. Sounds like development has stalled.

> You don't see an issue with switching the lib to TS?

You get that the consumer will see the js code right..? Have you even looked at the changes?

**Comment by NotSugden** [comment]
this needs to be done properly, it looks like you just renamed all the files to `x.ts` and added in a 'FIXME' type for anything you didnt know

this PR (in its current state, or in any state) would probably just make the intellisense worse

**Comment by OmgImAlexis** [comment]
Welcome to the third person that's not read this fully.

This was a **DRAFT** PR.

**Comment by OmgImAlexis** [comment]
It's like none of you have ever seen a work in progress PR before.

**Comment by OmgImAlexis** [comment]
1. This was a draft PR.
2. This changes almost nothing apart from a few exports and yet provides way better IntelliSense.
3. The FIXME comments are being worked on hence the draft PR.

I mean I could keep going but I doubt any of you even care since you're all just glossing right over this.

**Comment by OmgImAlexis** [comment]
So I'm going to keep working on this and then I'll re-open the PR. Heaven forbid I use a draft PR.

**Comment by tipakA** [comment]
For future, GitHub has an option to make a draft PR. This way everyone knows its a draft without need to add multiple lines saying so in the comment.

Also, just like it was already said, there is a separate repository for the Typescrpt rewrite of the lib.

**Comment by monbrey** [comment]
I'm fully aware that this is a draft, which is why I made no criticisms or judgements towards it's actual code.

I tried to provide advice as to the direction the maintainers of the library are taking with the TS rewrite, which you seem unwilling to take onboard.

If you wish to continue wasting hours of work on a direction that doesn't align with the goals and direction that lib development is taking, that's your decision.

**Comment by OmgImAlexis** [comment]
How is "This is not a TypeScript library." providing advice? Instead of "hey we're already working on a ts rewrite over here" you went with that.

So yeah.. it's definitely me that's "unwilling to take onboard". Maybe come in lest hostile next time? It's funny how I've been doing open source for ages and never had an issue yet the second I come in here I'm the problem. That doesn't exactly add up there bud. 😕

I saw an issue so I took it upon myself as most people do and followed your repo's guide for opening a PR. Let's take a look.

> If you wish to contribute to the discord.js codebase or documentation, feel free to fork the repository and submit a pull request.

**Comment by NotSugden** [comment]
you have good intentions here but IMO this PR is taking the wrong approach to it, i understand it was a draft PR, what i meant was just renaming all the files to .ts and dropping in the types as you go along sounds like it will get extremely messy, a rewrite is the best approach for converting to TypeScript (for a project like discord.js) IMO.

perhaps wait for a reply from a maintainer on if they want you to continue if you don't want to spend time on something that may not be merged, im just trying to be helpful

**Comment by iCrawl** [comment]
While the answers may have not be in the correct tone or style as I wished them to be, they are not wrong.

To answer a few of those additional questions:


> This also works right now as a drop-in replacement so I'm not 100% sure what the issue is.

A drop-in replacement with the library in its current state is a very undesirable approach to switch to TypeScript. There is no way we can 100% facilitate the benefits of it except "it's in Typescript now".

> "In development"... yeah there are PRs left in an almost empty state and it's been that way for months. Sounds like development has stalled.

Having worked in Open Source you should know this is completely normal. Working on a rewrite and a current version that will include breaking changes is a lot of effort, especially when you are still in the design-phase of it.
We have Discord channels specifically targeted to discussing potential additions or if people want to contribute to the complete ground up rewrite.

> It's funny how I've been doing open source for ages and never had an issue yet the second I come in here I'm the problem.

I am not a huge fan of the victim mentality here. The mentioned part was the unwillingness to understand what I posted as the answer in the first quote. It would be nice if we could keep this at least somewhat civil, thank you.

**Comment by 00100000spacebar** [comment]
Wow, discord.js pull request drama is honestly more exciting than any TV show.

**Pull request closed without merging**
