### PR TITLE
Change master to main for collection link

### PR DESCRIPTION
**Pull request by YodaLightsabr**
**Please describe the changes this PR makes and why it should be merged:**
Fixes a small bug in documentation (#7101), however this is a documentation issue, so I think it's reasonable to update this one line of code. Even though using v13 is the supported and preferred version to use, sometimes you need to look at v12 to see what changed in v13.

**Status and versioning classification:**

- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by ImRodry** [comment]
Pretty sure v12 doesn't get updates anymore, and thus PRs shouldn't be made to its branch

**Comment by YodaLightsabr** [comment]
Yes, but the documentation is generated from the source on GitHub.

**Comment by ImRodry** [comment]
Please see @kyranet's comment: https://github.com/discordjs/discord.js/issues/7101#issuecomment-991875907

**Comment by kyranet** [comment]
> Sometimes you need to look at v12 to see what changed in v13

No need, check our guide: https://discordjs.guide/additional-info/changes-in-v13.html#before-you-start

Closing this PR too since we do not accept changes to stable/deprecated versions.

**Pull request closed without merging**
