### PR TITLE
feat(Permissions): add new MODERATE_MEMBERS permission

### PR DESCRIPTION
**Pull request by milanmdev**
This PR adds the new MODERATE_MEMBERS permission

**Status and versioning classification:**

Please move lines that apply to you out of the comment:
- Code changes have been tested against the Discord API, or there are no code changes

### CODE REVIEW

**Comment by suneettipirneni** [comment]
This should probably be a part of PR #6949, rather than a separate PR.

**Comment by milanmdev** [comment]
Yeah I agree. Should I close this and mention this PR in that PR?

**Comment by suneettipirneni** [comment]
> Yeah I agree. Should I close this and mention this PR in that PR?

Yeah

**Comment by milanmdev** [comment]
Alright

**Pull request closed without merging**
