### PR TITLE
fix(ApplicationCommand): fix default member permissions assignment

### PR DESCRIPTION
**Pull request by CodeGoat-dev**
**Please describe the changes this PR makes and why it should be merged:**

Fixes default member permissions assignment when creating or editing application commands.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by imranbarbhuiya** [comment]
This isn't incorrect. If the key and value name is same, then u can write in shorten form. I.e.:

```ts
const a = 1;
const b = { a };
// is same as 
const b = { a: a}
```

**Comment by CodeGoat-dev** [comment]
> This isn't incorrect. If the key and value name is same, then u can write in shorten form. I.e.:
> 
> ```ts
> const a = 1;
> const b = { a };
> // is same as 
> const b = { a: a}
> ```

I accidentally submitted the wrong changes and only realised after your comment.
I guess I should have double checked what I was doing since I'm fully blind, but it's first thing in the morning. 😁

**Comment by ckohen** [comment]
What is this fixing?

There's code above the line you edited to take into account the differences in types between the two potential values.

**Comment by CodeGoat-dev** [comment]
> What is this fixing?
> 
> There's code above the line you edited to take into account the differences in types between the two potential values.

Using the latest dev release, application command creation and edit are throwing bigint serialisation errors for me regardless of whether my default member permissions are stringified or not.
This fixes my issue.

**Comment by ckohen** [comment]
Ah, I see. Curious how I missed this in testing.
Also curious that you can test this at all considering latest dev crashes on running.

Anyways, the proper fix here is to add .toString() tp the aforementioned previous code points, lines 232 and 238

**Review by ckohen — APPROVED** [review]

**Comment by CodeGoat-dev** [comment]
I resolved the crash in the latest dev release by removing the requirements for the missing integration scripts in client/websocket/handlers.

Anyway the recommended fix has been applied in the latest commit.

**Review by kyranet — APPROVED** [review]

**Comment by kyranet** [comment]
That's fixed in #8065, @CodeGoat-dev.

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
