### PR TITLE
typings(Embed): add missing getters and add video to EmbedData

### PR DESCRIPTION
**Pull request by BaumianerNiklas**
**Please describe the changes this PR makes and why it should be merged:**
This PR adds the author getter to the `Embed` typings which was previously missing. 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Review by bilgehanertan — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]
Can you double check nothing else is missing? LGTM otherwise

**Comment by BaumianerNiklas** [comment]
Whoops yeah, looks like there are still some other fields missing (specifically `hexColor`, `video`, `provider` and `length`). I'll add these shortly

**Comment by BaumianerNiklas** [comment]
I've now added the getters for `hexColors`, `provider` and `length`, but I don't know what to do about `video`. There is no `EmbedVideoData` interface in index.d.ts, I can't find the typedef [mentioned here](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/Embed.js#L91), and a `video` field also doesn't exist on `EmbedData`. Should it be removed from `Embed`, or should it be added to `Embed` and `EmbedData`? The Discord API docs [do say](https://discord.com/developers/docs/resources/channel#embed-object-embed-video-structure) that it exists.

**Comment by suneettipirneni** [comment]
> I've now added the getters for `hexColors`, `provider` and `length`, but I don't know what to do about `video`. There is no `EmbedVideoData` interface in index.d.ts, I can't find the typedef [mentioned here](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/Embed.js#L91), and a `video` field also doesn't exist on `EmbedData`. Should it be removed from `Embed`, or should it be added to `Embed` and `EmbedData`? The Discord API docs [do say](https://discord.com/developers/docs/resources/channel#embed-object-embed-video-structure) that it exists.

If it doesn't currently exist you can go ahead and define it.

**Review by SpaceEEC — APPROVED** [review]

**Comment by kyranet** [comment]
There are merge conflicts.

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
