### PR TITLE
Check for github action updates weekly

### PR DESCRIPTION
**Pull request by jlosito**
**Please describe the changes this PR makes and why it should be merged:**

This will use dependabot to check any github action this project uses for updates and submit pull requests with version bumps in order to keep dependencies up-to-date.

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Status and versioning classification:**

- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by imranbarbhuiya** [comment]
Does depandabot supports yarn v3?

**Comment by jlosito** [comment]
@imranbarbhuiya According to this, it only supports v1.

**Comment by imranbarbhuiya** [comment]
This repo uses yarn v3 so depandabot can't be used

**Comment by jlosito** [comment]
This change would only check against the github action dependencies which this project uses, not the javascript libraries. Are you saying that you're not interested in dependabot since it doesn't handle all of the dependency management which this project uses?

**Comment by jlosito** [comment]
@imranbarbhuiya dependabot can now support v3 starting today. A coincidence.

https://github.blog/changelog/2022-10-20-dependabot-can-now-generate-security-and-version-updates-for-yarn-v2-and-v3/

**Pull request closed without merging**
