### PR TITLE
Refactor(Structures): Allow the use of Structures outside Discord.JS DataStores

### PR DESCRIPTION
**Pull request by MrJacz**
**Please describe the changes this PR makes and why it should be merged:**
The PR aims to allow the use of Structures outside discord.js what I mean by that is, being able to use Structures.extend in frameworks where they might Datastores for some things.

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by appellation** [comment]
👎 this will allow discord.js users to extend structures that shouldn't be extended.

**Comment by bdistin** [comment]
This should also overwrite Map#delete() to throw an error instead of deleting anything. Same idea as the set method where already set classes should be protected from overwriting outside of the extend method.

**Comment by TeeSeal** [comment]
I don’t agree with this change. While the idea is cool this does not belong in discord.js. Providing functionality for extending custom user defined data structures is outside the scope of the library.

If you insist on this then a better way would be to expose the Structures class in the lib and let users instantiate their own Structures with whatever they want in it. Discord.Structures should only contain structures involved directly in the d.js library and should be frozen an such.

You don’t put your clothes in your server rack just because you can.

While we cannot completely prevent users from manipulating the data as they want, encouraging them to shove whatever they can vomit up into an object that the library internally relies on is wrong imo

**Comment by appellation** [comment]
I disagree with this PR:

## This doesn't need to exist

Discord.js is not intended for facilitating your storage solutions. We use data stores internally for storing Discord data and expose convenient functionality for extending said functionality. There is no purpose for people to add their own custom data stores which are never used within the library. If you happen to have a use-case where this behaviour is desired in your package, fortunately for you Discord.js ships with an Apache 2.0 license which grants you freedom to use and modify the source code. Enabling your storage convenience is far outside the scope of Discord.js.

## This implementation is poor

While I see what the goal is with overriding Map methods so people can't accidentally delete or override pre-existing structures, overriding Map methods is a huge concern for me. The Map behavior is standard across even languages and any situation where you need to change an industry standard is one where you should consider using a different standard.

## DataStores are not intended for arbitrary usage

The contents of DataStores must be very exact. Specifically, DataStores expect to contain objects and only objects; these objects can optionally have a `_patch` method which is called on `add` to update the internals of the object, and; these objects must have an `id` property or the ID resolution methods are likely to have undefined behaviour. Enabling an arbitrary Structures class would also entail supporting DataStores as a 1st class public citizen in Discord.js, which is *also* outside the scope of Discord.js. Considering the extreme specificity that DataStores are designed around, I would be against doing so even if it was within the scope of this library.

**Comment by bdistin** [comment]
I do agree with this pr. (less changes requested)

The implementation is 99% there, and this takes it that last 1%. [Hydra even stated intents for supporting custom DataStores](https://github.com/discordjs/discord.js/blob/master/src/stores/DataStore.js#L15) And Gawd already designed Structures so that an unlimited number of middlemen and the final consumer can extend structures made by DataStores. This just adds that last tiniest piece remaining (for custom structures to be registered) so middlemen can create custom DataStores and consumers can extend them.

**Comment by appellation** [comment]
Your citation of @amishshah as supporting this concept is a year and a half old and is likely referring to something that has since been implemented; @Gawdl3y began adding extendable structures shortly after this comment was made (cfa512c447469956d738df938137f97104734363), which leads me to believe that the "more extendable way to create their own custom datastores" is referring to what would become our Structures API.

As to the good design of the Structures API, I'm sure Gawdl3y appreciates the compliment but this is not really an argument in favor of extending the functionality. Just because capability exists to do something does not mean that it should be done: see my [previous comment](https://github.com/discordjs/discord.js/pull/3285#issuecomment-494487846) for reasoning on why.

**Comment by amishshah** [comment]
I don't have much else to add to this conversation, however I do agree with what @TeeSeal and @appellation have commented, I believe this is outside the scope of the library. I'm not quite sure where that leaves the ability to extend data structures though...

**Comment by iCrawl** [comment]
With a majority of rejections based on this PR and Stores now being Managers this PR would need a major overhaul, so if this is still wanted for some reason it needs to be a new PR.

**Pull request closed without merging**
