### PR TITLE
Support for interactionCreate event.

### PR DESCRIPTION
**Pull request by MatteZ02**
**Please describe the changes this PR makes and why it should be merged:**

Add support for interactionCreate event so us small people can still use slash-commands ourselves and get an event response from djs. All this includes is addition for the event.

**Status**

- [✅] Code changes have been tested against the Discord API, or there are no code changes
- [✅] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [✅] This PR changes the library's interface (methods or parameters added)
- [❌] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [❌] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Extroonie** [comment]
#5106 is already made which implements the full support though?

**Comment by MatteZ02** [comment]
I was just wondering as full support will be added in some version of v13. So why not just add support for the event before thats released.

**Comment by Extroonie** [comment]
> I was just wondering as full support will be added in some version of v13. So why not just add support for the event before thats released.

This will still need #4879 (support for gateway v8) which is indeed major and therefore needs v13. It also does not seem like there are any releases soon other than v13 though.

**Comment by MatteZ02** [comment]
> This will still need #4879 (support for gateway v8) which is indeed major and therefore needs v13. It also does not seem like there are any releases soon other than v13 though.

Interesting as i personally didn't change the gateway version on my fork and it works just fine with the event. Not sure what thats about.

**Comment by zaida04** [comment]
While Interactions are reported to work on v6, v6 is deprecated.

**Comment by advaith1** [comment]
neither this pr nor the full slash command pr needs v8 but v13 is gonna be the next version anyway; no need for this pr

**Pull request closed without merging**
