### PR TITLE
docs(chatInputApplicationCommandMention): parameters are not nullable

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**
https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/formatters/src/formatters.ts#L230-L240

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by jaw0r3k — CHANGES_REQUESTED** [review]
Actually only the first two are required
Dont take code out of context
https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/formatters/src/formatters.ts#L217-L220

**Comment by jaw0r3k** [comment]
even the lines below say it
https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/formatters/src/formatters.ts#L240-L249

**Comment by almeidx** [comment]
> Actually only the first two are required

Meaning the rest of the parameters are optional, not nullable

**Comment by jaw0r3k** [comment]
> Meaning the rest of the parameters are optional, not nullable

Ups yeah sorry

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by Jiralite — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
