### PR TITLE
fix(ClientOptions): make `ClientOptions#intents` returns an IntentsBitField

### PR DESCRIPTION
**Pull request by Idris1401**
**Please describe the changes this PR makes and why it should be merged:**

I think it's better that `ClientOptions#intents` returns an instance of IntentsBitField instead of just a number.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by almeidx** [comment]
https://github.com/discordjs/discord.js/blob/7a9e52e63a369196ab94920669aaa5e34969fa0d/packages/discord.js/src/client/websocket/WebSocketShard.js#L690

`intents: client.options.intents.bitfield,`

***

https://github.com/discordjs/discord.js/blob/7a9e52e63a369196ab94920669aaa5e34969fa0d/packages/discord.js/src/client/websocket/WebSocketShard.js#L515

` const hasGuildsIntent = this.manager.client.options.intents.has(GatewayIntentBits.Guilds); `

**Review by Jiralite — COMMENTED** [review]
If this is to be standardised, I guess the type when being accessed could be `Omit<ClientOptions, "intents"> & { intents: IntentsBitField };`?

**Comment by Idris1401** [comment]
> If this is to be standardised, I guess the type when being accessed could be `Omit<ClientOptions, "intents"> & { intents: IntentsBitField };`?

instead of `BitFieldResolvable<GatewayIntentsString, number>` (at [line 4269 of index.d.ts](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/typings/index.d.ts#L4269))

**Comment by almeidx** [comment]
No, here

https://github.com/discordjs/discord.js/blob/7a9e52e63a369196ab94920669aaa5e34969fa0d/packages/discord.js/typings/index.d.ts#L757

**Review by vladfrangu — APPROVED** [review]

**Comment by Jiralite** [comment]
Please double-check the tests!

**Review by Jiralite — COMMENTED** [review]
Would this need changing too?

https://github.com/discordjs/discord.js/blob/abb7226af3445f5b724815bb2f7a121a52a563b5/packages/discord.js/src/client/websocket/WebSocketShard.js#L695

Previously, this emitted the bit field. However, it now emits the class (`IntentsBitField { bitfield: 8192 }` for example). It doesn't seem problematic either way.

**Review by Jiralite — APPROVED** [review]

**Comment by Idris1401** [comment]
> ~~Would this need changing too?~~
> 
> 
> 
> https://github.com/discordjs/discord.js/blob/abb7226af3445f5b724815bb2f7a121a52a563b5/packages/discord.js/src/client/websocket/WebSocketShard.js#L695
> 
> 
> 
> ~~Previously, this emitted the bit field. However, it now emits the class (`IntentsBitField { bitfield: 8192 }` for example). It doesn't seem problematic either way.~~

so no need to change it? ._.

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
