### PR TITLE
build: Bump versions

### LINKED ISSUE #9985: Property '#private' in type 'REST' refers to a different member that cannot be accessed from within type 'REST'.
### Which package is this bug report for?

create-discord-bot

### Steps
1. Do `yarn create discord-bot`.
2. In options use typescript.
3. In src/util/deploy.ts, error occurs.

```
Argument of type 'import("(location of bot code)/node_modules/@discordjs/rest/dist/index").REST' is not assignable to parameter of type 'import("(location of bot code)/node_modules/@discordjs/rest/dist/index", { assert: { "resolution-mode": "import" } }).REST'.
  Property '#private' in type 'REST' refers to a different member that cannot be accessed from within type 'REST'.ts(2345)
```

### Code sample

```typescript
import process from 'node:process';
import { URL } from 'node:url';
import { API } from '@discordjs/core/http-only';
import { REST } from 'discord.js';
import { loadCommands } from './loaders.ts';

const commands = await loadCommands(new URL('../commands/', import.meta.url));
const commandData = [...commands.values()].map((command) => command.data);

const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_TOKEN!);
const api = new API(rest);

const result = await api.applicationCommands.bulkOverwriteGlobalCommands(process.env.APPLICATION_ID!, commandData);

console.log(`Successfully registered ${result.length} commands.`);
```

### Versions

- discord.js@14.14.1
- typescript@5.2.2
- node v20.8.0

### Issue priority

Low (no impact on functionality)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

_No response_

### PR DESCRIPTION
**Pull request by Jiralite**
Bumps dependencies.

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Comment by jaw0r3k** [comment]
Doesnt seem working for me...

Updated versions:
image

image

**Comment by vladfrangu** [comment]
@jaw0r3k please `npm ls @discordjs/rest` 🙏

**Comment by mallusrgreatv2** [comment]
> @jaw0r3k please `npm ls @discordjs/rest` 🙏

I also have the same issue:
`├─┬ @discordjs/core@1.1.1
│ ├── @discordjs/rest@2.2.0
│ └─┬ @discordjs/ws@1.0.2
│   └── @discordjs/rest@2.2.0 deduped
└─┬ discord.js@14.14.1
  └── @discordjs/rest@2.2.0 deduped
`

**Comment by vladfrangu** [comment]
PR is blocked till we get a resolution for https://github.com/microsoft/TypeScript/issues/56455 🤞

**Comment by ckohen** [comment]
For those that find this PR before that is resolved, a solution is importing directly from `@discordjs/rest` since it has exports for both module types that TS resolves properly.

**Comment by darionbuilds** [comment]
> PR is blocked till we get a resolution for [microsoft/TypeScript#56455](https://github.com/microsoft/TypeScript/issues/56455) 🤞

Just as an FYI, this was marked as working as intended on the TS repo.

**Comment by ckohen** [comment]
Which unfortunately means my previous suggestion is the best way to overcome this. I think we plan on making it work by faking djs having esm support in TS land, which is incredibly dumb, and balloons the package size for literally no reason, but alas.

**Comment by Jiralite** [comment]
#10009 was raised to fix #9985, so this will just bump dependencies.

**Review by suneettipirneni — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
