### PR TITLE
feat: error code 180001

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

- https://github.com/discord/discord-api-docs/pull/4082

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Review by kyranet — APPROVED** [review]
Let's wait for the upstream PR to merge first.

**Review by vladfrangu — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Comment by iShibi** [comment]
error is missing from jsdoc comment in Constants

**Comment by suneettipirneni** [comment]
> error is missing from jsdoc comment in Constants

I added this in, but there are like five other errors not documented should they be added as well?

**Comment by iCrawl** [comment]
Yes please, even if its a bit out of scope, you can just expand the scope of the PR a bit

**Comment by kyranet** [comment]
While the upstream PR was closed, you can keep this one and re-purpose it for the docs changes.

**Pull request closed without merging**
