### PR TITLE
Revert #6102 (see #6681)

### PR DESCRIPTION
**Pull request by alula**
**Please describe the changes this PR makes and why it should be merged:**

Revert changes made in pull request #6102, which causes bundlers like webpack to break (#6681).

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by vladfrangu** [comment]
Why? We do not support webpack and have stopped supporting it ever since we removed browser support.

**Comment by alula** [comment]
This is a pretty trivial change and Webpack isn't only used in browser environments.

**Comment by alula** [comment]
actually for some context read from here: https://discord.com/channels/222078108977594368/682166281826598932/890684079186530364

**Comment by alula** [comment]
The raised concern seems to be caused by "less maintainable code" and "often forgetting to export things". 
I proposed a slightly different approach - add tests that check if all modules in the directory are referenced properly - which also might seem help with similar issues in other parts of the library.

**Pull request closed without merging**
