### PR TITLE
fix(Message): do not locally call reaction add handler

### LINKED ISSUE #4284: client.on('messageReactionAdd') is firing twice for reactions added by BOTs
The 'messageReactionAdd' event fires twice for reactions added by bots

```js
client.on('messageReactionAdd', (messageReaction, user) => {
  console.log('test');
});
// 'test' logs twice in the console
// that is the only listener in all of my code for 'messageReactionAdd'
```

**Further details:**
- discord.js version: 12.2.0
- Node.js version: 14
- Operating system: Windows 10
- Priority: idk
- [] I have also tested the issue on latest master, commit hash:

### PR DESCRIPTION
**Pull request by geniusjam**
**Please describe the changes this PR makes and why it should be merged:**
This fixes #4284
**Status**

- [ ] Code changes have been tested against the Discord API, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by RDambrosio016** [comment]
This is a breaking change, the `count` of the reaction returned will not be updated with the actual count in the initial return value. For example having a bot call react on a message, the count does not account for that reaction, and the count will be 1 less than the actual user count.

You should also be completing the pull request template, it is there for a reason. And this should have been more thoroughly tested to catch this issue. 

Reproducible code:
```js
let reaction = await <Message>.react("❌");
console.log(reaction.count); // 1 in djs-master, 0 in this PR```

**Comment by geniusjam** [comment]
It should be fixed now.

**Comment by geniusjam** [comment]
Looking at #4316, this PR probably won't be pushed because #4316 needs a different implementation of the react method.

**Comment by SpaceEEC** [comment]
The references issue has been resolved by #4682, therefore closing this pull request.

**Pull request closed without merging**
