### PR TITLE
docs: Update Node.js requirement to 16.11.0

### PR DESCRIPTION
**Pull request by AnxietyisReal**
**Please describe the changes this PR makes and why it should be merged:**
I believe this is the only place that hasn't updated to match the rest of the locations, help channel in Discord also says 16.11 is required.

**Status and versioning classification:**

This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Jiralite** [comment]
I think this should be updated everywhere (engines, other README.mds, etc.).

**Comment by AnxietyisReal** [comment]
Right so, I should be replacing v16.9.0 in other files/locations with 16.11.0? Including ones in package.json, README.md and mdx files?

**Comment by Jiralite** [comment]
Yes.

**Review by Jiralite — APPROVED** [review]
One more:

https://github.com/discordjs/discord.js/blob/83801a4ef794e34d2400d40e9d129ac97a368620/apps/guide/src/content/05-additional-info/03-updating-to-v14.mdx#L10

**Comment by AnxietyisReal** [comment]
Thanks, forgot that as well.

**Review by iCrawl — APPROVED** [review]

**Review by suneettipirneni — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Comment by AnxietyisReal** [comment]
I would assume it isn't going to be merged automatically because Tests are failing twice during packages/ui build..?

**Comment by Jiralite** [comment]
That's right. #9772 should resolve this.

**Review by sdanialraza — APPROVED** [review]

**Pull request merged**
