### PR TITLE
typings: make `channelId` non-nullable on `MessageComponentInteraction`

### LINKED ISSUE #6591: Feature request: Make `MessageComponentInteraction#channelId` non-nullable
### Feature

Currently `MessageComponentInteraction#channelId` is nullable.

However, the Discord API documentation states that it is
> For Message Components it includes identifying information about the component that was used. It will also include some metadata about how the interaction was triggered: the `guild_id`, `channel_id`, `member` and other fields. You can find all the values in our data models.
> -from: https://discord.com/developers/docs/interactions/receiving-and-responding#interactions

From this, `MessageComponentInteraction#channelId` can be non-nullable.

### Ideal solution or implementation

Make `MessageComponentInteraction#channelId` non-nullable.

### Alternative solutions or implementations

_No response_

### Other context

_No response_

### PR DESCRIPTION
**Pull request by suneettipirneni**
**Please describe the changes this PR makes and why it should be merged:**

Closes #6591, references: https://discord.com/developers/docs/interactions/receiving-and-responding#interactions

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by monbrey** [comment]
How is `member` non-nullable? Can components not be sent / interacted with in DMs?

**Comment by suneettipirneni** [comment]
> How is `member` and `guildId` non-nullable? Can components not be sent / interacted with in DMs?

Good catch, this has been reverted.

**Comment by Jiralite** [comment]
I believe the documentation should be edited to reflect these changes, no?

**Comment by suneettipirneni** [comment]
> I believe the documentation should be edited to reflect these changes, no?

Updated 😄

**Review by SpaceEEC — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
