### PR TITLE
Update Util.js

### PR DESCRIPTION
**Pull request by MrScopes**
**Please describe the changes this PR makes and why it should be merged:**
Asterisks and Underscores are "filtered" in cleanContent now. So, \\_ and \\*

**Status**
- [x] Code changes have been tested against the Discord API
- [x] Typings don't need updated.

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by MrScopes** [comment]
```/home/travis/build/discordjs/discord.js/src/util/Util.js
  396:23  error  Unnecessary escape character: \_  no-useless-escape```
It's not a useless escape.

**Comment by kyranet** [comment]
You meant `\\_`. `\_` translates to `_` in JavaScript's strings.

**Comment by Gawdl3y** [comment]
This is not the point of cleanContent. cleanContent is to escape mentions in the message, not markdown. If you want to escape markdown, use [Util.escapeMarkdown](https://discord.js.org/#/docs/main/stable/class/Util?scrollTo=s-escapeMarkdown).

**Comment by SpaceEEC** [comment]
Closing, see ^

**Pull request closed without merging**
