### PR TITLE
feat(ClientPresence): allow setting activity state

### PR DESCRIPTION
**Pull request by advaith1**
**Please describe the changes this PR makes and why it should be merged:**

custom status for bots!

* https://github.com/discord/discord-api-docs/pull/6345

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by jaw0r3k** [comment]
What about this one?

https://github.com/discordjs/discord.js/blob/7295a3a94a853086f781e7810b37c77d0c7e5283/packages/discord.js/src/structures/ClientPresence.js#L64-L69

**Comment by advaith1** [comment]
oops, thanks!

**Comment by advaith1** [comment]
since `name` is required but not displayed for custom status, currently you would need to something like this which is not the best dx
```js
client.user.setActivity('Custom Status', { state: 'hello world', type: ActivityType.Custom })
```
```js
client.user.setActivity({ name: 'Custom Status', state: 'hello world', type: ActivityType.Custom })
```
(the client uses "Custom Status" for the `name`, though anything works)

so some things we can do are:
1. make the `name` field optional and default it to "Custom Status" for custom status activities
but the code might be messy, since `name` is currently required
```js
client.user.setActivity({ state: 'hello world', type: ActivityType.Custom })
```

2. default `state` to `name` for custom status activities
in this case we could set `name` to "Custom Status" or just leave it as-is
```js
client.user.setActivity('hello world', { type: ActivityType.Custom })
```
```js
client.user.setActivity({ name: 'hello world', type: ActivityType.Custom })
```

3. add a setCustomStatus method that calls setActivity internally
```js
client.user.setCustomStatus('hello world')
```

which one should we go with? or should we just leave it as it currently is, requiring `name` and `state` for custom status

**Comment by advaith1** [comment]
ready for review! looking for maintainer feedback about abstracting custom status ^

**Comment by vladfrangu** [comment]
I'm semi leaning towards 2 *and* 3, but lets wait for other maintainers to give their thoughts too

**Comment by Jiralite** [comment]
`name` as a required field for custom status sounds like something that should be raised to the Discord developers to see if they can change that. Has that been done already?

**Comment by jaw0r3k** [comment]
Custom activity actually doesnt need name
so you can check for that in this pice of code https://github.com/discordjs/discord.js/blob/81530ddbb8e230c42fe0cdd5e417927f9a235d33/packages/discord.js/src/structures/ClientPresence.js#L51-L53

**Comment by Jiralite** [comment]
I would opt for 2, also just in case `state` becomes something usable in the future for custom statuses.

@vladfrangu I probably wouldn't go for 3 because it might be an incentive to create methods for other activity types.

<hr>

Just looking at [the method](https://old.discordjs.dev/#/docs/discord.js/main/class/ClientUser?scrollTo=setActivity) now... feels like both parameters should be consolidated into one `ActivityOptions`.

**Comment by theredcmdcraft** [comment]
Maybe a stupid question but what about emojis with custom status?

**Comment by Jiralite** [comment]
Emojis cannot be used.

**Comment by jaw0r3k** [comment]
> Maybe a stupid question but what about emojis with custom status?

They probably wont be added https://github.com/discord/discord-api-docs/pull/6345#issuecomment-1670887462

**Comment by theredcmdcraft** [comment]
> Emojis cannot be used.

Because of Discord Limitations? I\`ve tried a little bit with emojis. I`ve used the following gateway json: 
```
{
  "op": 3,
  "d": {
    "since": 91879201,
    "activities": [
      {
        "name": "galaxybot.app",
        "type": 4,
        "state": "galaxybot.app",
        "emoji": {
          "name": "smiley"
        }
      }
    ],
    "status": "online",
    "afk": false
  }
}
```

This Json I had sended to the discord gateway over the websocket. What I know you got instantly disconnected if your json is wrong, but i got not disconnected and the bot does not had an emoji. So my assumption is therefore, that the Discord Client, cannot display it, because it is a Bot User.

**Comment by iCrawl** [comment]
Option 2 sounds fine to me too.

**Comment by vladfrangu** [comment]
> discord/discord-api-docs#6345 (comment)

FWIW `name` needs to be unicode and not the name of the emoji. That said, I doubt Discord allows it for bots (due to the nature of permission checking alone)

**Comment by advaith1** [comment]
implemented option 2 and tested

https://github.com/discordjs/discord.js/blob/a9a3ed0643cbdfd8ed71f803e57be4cdace294d4/packages/discord.js/src/structures/ClientPresence.js#L57-L60

**Review by kyranet — APPROVED** [review]

**Comment by GeekCornerGH** [comment]
Is there any chance this lands in v14 before v15 releases?

**Comment by kyranet** [comment]
v15's release isn't happening anytime soon, we're still working on v14, and this is a v14 PR.

**Comment by GeekCornerGH** [comment]
> v15's release isn't happening anytime soon, we're still working on v14, and this is a v14 PR.

Fair enough, thanks!

**Review by Jiralite — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
