### PR TITLE
feat(GuildMemberManager): add `GuildMemberManager#fetchMe()`

### PR DESCRIPTION
**Pull request by Syjalo**
**Please describe the changes this PR makes and why it should be merged:**
There is property `GuildMemberManager#me` and it can be `null`. And to fetch the client user you should do `guild.members.fetch(guild.client.user.id)`.
This PR makes much easier to fetch client user as GuildMember of the guild.

Example:
```js
if (!guild.members.me) {
  await guild.members.fetchMe();
}
```

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by ImRodry** [comment]
You will always receive your bot’s GuildMember object on every guild and this just sounds like a lazy shortcut, I don’t see a point in this

**Comment by Syjalo** [comment]
> You will always receive your bot’s GuildMember object on every guild

You won't receive it if the `Guilds` intent is not enabled.

> This just sounds like a lazy shortcut

So `Guild#fetchOwner()` is also a lazy shortcut?

**Comment by almeidx** [comment]
> You will always receive your bot’s GuildMember object on every guild 

`Guild#me` is a getter that relies on the cache, and because of sweepers it might not always be present

**Comment by ImRodry** [comment]
> You won't receive it if the Guilds intent is not enabled.

You need the Guilds intent for basically everything else with a bot so I still don’t understand the need for this

> So Guild#fetchOwner() is also a lazy shortcut?

yes but at least that one has a reasoning behind it which is that the ownerId is provided by Discord so you need a way to fetch it because you may not always have it. For Guild#me it will always be there

> Guild#me is a getter that relies on the cache, and because of sweepers it might not always be present

It’s there to begin with. If you choose to remove it then that’s an issue you gotta sort out, that’s why it’s documented as nullable

**Comment by ObscuritySRL** [comment]
> You need the Guilds intent for basically everything

Correct me if I'm wrong, but can bots not receive and respond to interactions without `Guilds`? If your bot doesn't involve any form of guild moderation, interactions will often times contain all the information you need — guild Id, member info, roles, and permissions, etc.

**Comment by ImRodry** [comment]
> > You need the Guilds intent for basically everything
> 
> Correct me if I'm wrong, but can bots not receive and respond to interactions without `Guilds`? If your bot doesn't involve any form of guild moderation, interactions will often times contain all the information you need — guild Id, member info, roles, and permissions, etc. Unique case, sure, but AFAIK one where `Guilds` is not required.

If you don’t have the Guilds intent you won’t have guilds where you can use this method in, because Discord doesn’t send them

**Comment by ObscuritySRL** [comment]
> > > You need the Guilds intent for basically everything
> > 
> > 
> > Correct me if I'm wrong, but can bots not receive and respond to interactions without `Guilds`? If your bot doesn't involve any form of guild moderation, interactions will often times contain all the information you need — guild Id, member info, roles, and permissions, etc. Unique case, sure, but AFAIK one where `Guilds` is not required.
> 
> If you don’t have the Guilds intent you won’t have guilds where you can use this method in, because Discord doesn’t send them

Forgot about this. Would it not still be possible to do `const me = new Guild(client, {id: someGuildId}).fetchMe()`? Still not sure how useful that'd be - I haven't used DJS apart from API types recently, but I recall doing something similar to add channel followers when I wasn't caching them a while back.

**Review by vladfrangu — APPROVED** [review]
I'm 🤷 on this

**Comment by vladfrangu** [comment]
> > If you don’t have the Guilds intent you won’t have guilds where you can use this method in, because Discord doesn’t send them
> 
> Forgot about this. Would it not still be possible to do `const me = new Guild(client, {id: someGuildId}).fetchMe()` to get member info about the client user? Still not sure how useful that'd be - I haven't used DJS apart from API types recently, but I recall doing something similar to add channel followers when I wasn't caching them a while back.
> 
> **Edit**: Correction - at the time it was easiest to add a channel follower for a channel on another shard with `new Channel(...).addFollower()` or whatever.

That points a lot to the fact there's still tons of methods not accessible to managers and only to built structures, which is something we need to fix in the future

**Comment by kyranet** [comment]
Come think of it, shouldn't we do `guild.members.fetchMe()` instead of `guild.fetchMe()`?

We could also move `guild.me` to `guild.members.me` in another PR.

**Comment by Syjalo** [comment]
> Come think of it, shouldn't we do `guild.members.fetchMe()` instead of `guild.fetchMe()`?
> 
> We could also move `guild.me` to `guild.members.me` in another PR.

I think so. We could also move `guild.fetchOwner()`.

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Comment by BenPatersonxx** [comment]
@iCrawl @SpaceEEC please review

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
