### PR TITLE
feat v13: add new flags

### PR DESCRIPTION
**Pull request by jaw0r3k**
**Please describe the changes this PR makes and why it should be merged:** 
Adds all new flags (without ChannelFlags as the are in  #8651)
**Status and versioning classification:**

This pr includes unstable properties ( not documented yet )

### CODE REVIEW

**Comment by jaw0r3k** [comment]
wait typings

**Comment by Qjuh** [comment]
Only three of those six flags are documented. Don’t add undocumented flags, as they may change any time and would introduce breaking changes.

**Comment by jaw0r3k** [comment]
> 

yeah thats what i said in pr status

**Comment by MrMythicalYT** [comment]
> yeah thats what i said in pr status

discord.js does not use undocumented features, since they are either unstable, or unpredictable.

**Comment by Jiralite** [comment]
If you include only the supported flags, this pull request would be fine.

**Comment by Jiralite** [comment]
Superseded by #9473.

**Pull request closed without merging**
