### PR TITLE
added DARK_MODE_INVISIBLE

### PR DESCRIPTION
**Pull request by Fyk0**
This PR ads another color to the constants that makes embeds appear as *invisible* on Dark Mode.
image

### CODE REVIEW

**Comment by S0ftwareUpd8** [comment]
why is this needed

**Comment by devsnek** [comment]
these colour constants come from discord's branding and the built-in role colour picker. `DARK_BUT_NOT_BLACK` is used as the bg color of the client.

**Comment by Monbrey** [comment]
https://discordapp.com/branding

As referred to above

**Comment by amishshah** [comment]
Sorry, would be inconsistent to add this!

**Pull request closed without merging**
