### PR TITLE
fix(Typings): Missing user definition

### PR DESCRIPTION
**Pull request by iAmZiNc**
**Please describe the changes this PR makes and why it should be merged:**

On guildBanAdd + guildBanRemove events, the "user" property is not included in the typings.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by iAmZiNc** [comment]
Oh goodness, why did it include all those merge commits?

**Comment by DTrombett** [comment]
There's no `user` parameter passed to those events..

**Comment by iAmZiNc** [comment]
> 
> 
> There's no `user` parameter passed to those events...
> 
> https://github.com/discordjs/discord.js/blob/07017a9699eecc4af7824ace39dd91e8b689f3c6/src/client/actions/GuildBanAdd.js#L16
> 
> https://github.com/discordjs/discord.js/blob/07017a9699eecc4af7824ace39dd91e8b689f3c6/src/client/actions/GuildBanRemove.js#L20

Hm... are you sure?

https://discord.js.org/#/docs/main/master/class/Client?scrollTo=e-guildBanAdd
https://discord.js.org/#/docs/main/master/class/Client?scrollTo=e-guildBanRemove

Either the docs are wrong, or the typings are wrong. I think you're correct, from what it shows there, but the docs should be revised in this case.

**Comment by iAmZiNc** [comment]
Oh, I believe I must've had a cached version of the page. A hard refresh and... poof, they're gone. When were they removed?

**Comment by iAmZiNc** [comment]
Unnecessary, the parameters actually no longer exist.

**Pull request closed without merging**
