### PR TITLE
feat(EmbedBuilder): add `.length`

### LINKED ISSUE #8647: Adding a string length property to embeds builders
### Which package is the feature request for?

discord.js

### Feature

In v13 you used to be able to use .length to get the total text length of all the text in an embed (author, title, description, fields, etc.) but in v14 this was not added to the EmbedBuilder, and thus there doesn't appear to be a way to get this information now without doing it manually. From what I've heard it seems to be still returned from the API, so it doesn't seem like it'd be too hard to add back in.

### Ideal solution or implementation

When using .length on an EmbedBuilder, it should return the total text length of the entire embed from the API.

### Alternative solutions or implementations

_No response_

### Other context

_No response_

### PR DESCRIPTION
**Pull request by RedGuy12**
**Please describe the changes this PR makes and why it should be merged:**
Resolves #8647 
**Status and versioning classification:**

- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by RedGuy12** [comment]
Could I get a review on this?

**Comment by iCrawl** [comment]
Wouldn't it be fine if users just do:

```ts
import { embedLength } from '@discordjs/builders`;

embedLength(YourEmbedBuilderInstance.toJSON());
```
?

**Comment by RedGuy12** [comment]
> Wouldn't it be fine if users just do

Yes, but why does [Embed have a length property](https://github.com/discordjs/discord.js/blob/9d8179c6a78e1c7f9976f852804055964d5385d4/packages/discord.js/src/structures/Embed.js#L183) then?

**Comment by kyranet** [comment]
I'm against this change, it goes against [RFC](https://github.com/discordjs/discord.js/issues/8015) about exposing a builder's data via getters:

> Well I changed my mind, we should instead use the `data` field, however no getters should be added pointing to said field.

**Review by Jiralite — CHANGES_REQUESTED** [review]
Can you add typings?

**Review by vladfrangu — APPROVED** [review]

**Review by Jiralite — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Pull request merged**
