### PR TITLE
feat: return entries instead of values in toJSON method

### LINKED ISSUE #9310: Change `collection#toJSON` to return `entries` instead of `values` only
### Which package is this feature request for?

collection

### Feature

I'm not sure what's the exact reason for returning only values from `collection` but this makes creating a collection from `toJSON` output impossible. For djs internal collections, id is present in values too so we don't get any issues. But when using with anything else where key and value are different and we do `toJSON` (or `JSON.stringify` when sharing data from one process to another), we only get the values and all the keys get lost. Returning `entries` will save the keys and we'll be able to construct a new collection/map from the returned data.

### Ideal solution or implementation

https://github.com/discordjs/discord.js/blob/e2f39ccc32c3a404a7261ea6820bf428cee909b9/packages/collection/src/collection.ts#L797-L800

```ts
	public toJSON() {
		// toJSON is called recursively by JSON.stringify.
		return [...this.entries()];
	}
```

### Alternative solutions or implementations

use entries manually before using stringify

### Other context

_No response_

### PR DESCRIPTION
**Pull request by Shiva953**
**Please describe the changes this PR makes and why it should be merged:**
This PR modifies the toJSON method in the collection package to return entries instead of just values. Currently, the toJSON method only returns values from the collection, which makes it impossible to create a new collection from the JSON output.

To fix this issue, this PR modifies the toJSON method to return entries instead of just values. This will preserve the keys and allow the creation of a new collection/map from the returned data. (FIXES #9310 ).

**Status and versioning classification:**
    - Code changes have been tested against the Discord API, or there are no code changes
    - This PR changes the library's interface (methods or parameters added)
    - (Status Classification) This PR includes breaking changes (method(s) removed or renamed, parameters moved or removed)

Please review this PR and let me know if any changes are required.

### CODE REVIEW

**Comment by jaw0r3k** [comment]
Well it's a braking change, SL you should mention about it

**Comment by Shiva953** [comment]
> Well it's a braking change, so you should mention about it

Can you please Elaborate on what I should mention?

**Comment by jaw0r3k** [comment]
> Can you please Elaborate on what I should mention?

The status classification
`- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)`

**Comment by Shiva953** [comment]
> > Can you please Elaborate on what I should mention?
> 
> The status classification
> `- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)`

Done👍

**Review by vladfrangu — APPROVED** [review]
Makes sense, but yes, very breaking

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — CHANGES_REQUESTED** [review]
Tests needs updating

**Review by didinele — APPROVED** [review]

**Comment by kyranet** [comment]
@Shiva953 your branch update missed updating `toJSON()`'s tests, [CI](https://github.com/discordjs/discord.js/actions/runs/6414858017/job/17425899541?pr=9345#step:9:83) is reporting errors:

image

**Review by Jiralite — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
