### PR TITLE
issue when providing a lowercase color name

### PR DESCRIPTION
**Pull request by BannerBomb**
**Please describe the changes this PR makes and why it should be merged:**
The changes made are to change the color string to upper case since that's how they are written in the Constants file to fix an issue that when trying to use lower case names it will output NaN instead of the color.

An example of what I mean
image

**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Papaia** [comment]
Well, this is intentional.
If you look at the docs for [`ColorResolvable`](https://discord.js.org/#/docs/main/stable/typedef/ColorResolvable), it is clear that the strings are upper case, similarly to BitField flags (see [`Permissions.FLAGS`](https://discord.js.org/#/docs/main/master/class/Permissions?scrollTo=s-FLAGS) for example).
This is not an issue, and also not a bug.

**Comment by BannerBomb** [comment]
Yes, but permissions throw an error if it's not able to be resolved while colors just returns you a NaN since the value you provided is passed into the parseInt function.

**Comment by Papaia** [comment]
It should throw, so this is an issue on its own, but my point is still relevant, this is intentional in that that it does not allow lowercase string.

**Comment by Papaia** [comment]
It would be breaking to fix it to throwing at this point, so that's a no.
But it is still not supposed to support lowercase color names so this PR is still probably not going to be merged.

**Comment by almostSouji** [comment]
The enum-like behaviour here allowing only uppercase strings to be used is deliberate as also the [typings](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L2358) attest.

For consistencies sake this should probably throw, however the method has this behavior for [over 3 years now](https://github.com/discordjs/discord.js/pull/1517/files) (and before that it was just in a different location), and changing this would definitely be considered a breaking semver major, meaning it will earliest be considered for the planned rewrite/v13.

**Pull request closed without merging**
