### PR TITLE
👌

### PR DESCRIPTION
**Pull request by darwinikii**
**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

### CODE REVIEW

**Comment by SuperchupuDev** [comment]
this will throw a syntax error lol, the current code isn't even broken

**Comment by darwinikii** [comment]
~/lastjs-music$ node index.js
/home/runner/lastjs-music/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'

i am getting this error

**Comment by SuperchupuDev** [comment]
> ~/lastjs-music$ node index.js
> /home/runner/lastjs-music/node_modules/discord.js/src/rest/RESTManager.js:32
> const token = this.client.token ?? this.client.accessToken;
> ^
> 
> SyntaxError: Unexpected token '?'
> 
> i am getting this error

update to node 16.6

**Comment by darwinikii** [comment]
I can't update because I'm using repl.it :(

**Comment by SuperchupuDev** [comment]
> I can't update because I'm using repl.it :(

ask repl.it, not djs related

**Comment by darwinikii** [comment]
thanks

**Pull request closed without merging**
