### PR TITLE
ci: validate typings

### PR DESCRIPTION
**Pull request by oceanroleplay**
**Please describe the changes this PR makes and why it should be merged:**

- CI will prevent issues like https://github.com/discordjs/discord.js/pull/6910
- Accidental merge will not performed if above issue found in any PR.

**Status and versioning classification:**

- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by oceanroleplay** [comment]
tests will now pass since #6910 merged.

**Comment by suneettipirneni** [comment]
@oceanroleplay I'm not clear as to what this adds, as you stated in the comment above the tests are properly compiling code, so what does this PR aim to change/add?

**Comment by oceanroleplay** [comment]
> This PR will not pass Tests/TypeScript because of #6910 please see https://github.com/discordjs/discord.js/runs/4042464107?check_suite_focus=true

@suneettipirneni type validation to prevent issue like this.

**Comment by oceanroleplay** [comment]
> @oceanroleplay I'm not clear as to what this adds, as you stated in the comment above the tests are properly compiling code, so what does this PR aim to change/add? `npx tsc` compiles all of the TS files.

it won't compile to js because of noemit flag, it will just validate it.

**Comment by suneettipirneni** [comment]
> > This PR will not pass Tests/TypeScript because of #6910 please see https://github.com/discordjs/discord.js/runs/4042464107?check_suite_focus=true
> 
> @suneettipirneni type validation to prevent issue like this.

So after looking at the configuration, the only change that needs to be made in this PR is that in the `package.json`, `test:typescript` should be `npx tsc --skipLibCheck false --noEmit`, instead of `npx tsc --noEmit`.

**Comment by oceanroleplay** [comment]
> > > This PR will not pass Tests/TypeScript because of #6910 please see https://github.com/discordjs/discord.js/runs/4042464107?check_suite_focus=true
> > 
> > 
> > @suneettipirneni type validation to prevent issue like this.
> 
> So after looking at the configuration, the only change that needs to be made in this PR is that in the `package.json`, `test:typescript` should be `npx tsc --skipLibCheck false --noEmit`, instead of `npx tsc --noEmit`.
> 
> The other changes can be reverted.

yes, updated `skipLibCheck` to `false` in `tsconfig.json`. here is a sample test with updated changes.

image

**Comment by suneettipirneni** [comment]
I originally meant to use the CLI option of `--skipLibCheck false`, there's been reported issues with `skipLibCheck`, however I'll leave the maintainers to give input on this change.

**Comment by oceanroleplay** [comment]
> I originally meant to use the CLI option of `--skipLibCheck false`, there's been reported issues with `skipLibCheck` being used in the `tsconfig` directly, however I'll leave the maintainers to give input on this change.

okay, can you give me references to issues that being reported?. However, I updated cli option, if this is the case.

**Comment by suneettipirneni** [comment]
> > I originally meant to use the CLI option of `--skipLibCheck false`, there's been reported issues with `skipLibCheck` being used in the `tsconfig` directly, however I'll leave the maintainers to give input on this change.
> 
> okay, can you give me references to issues that being reported?. However, I updated cli option, if this is the case.

https://discord.com/channels/222078108977594368/222197033908436994/867523134152638528

**Comment by suneettipirneni** [comment]
Ignore my previous comment(s), editing the tsconfig directly will be fine.

**Comment by oceanroleplay** [comment]
> Ignore my previous comment(s), editing the tsconfig directly will be fine.

reverted changes to `tsconfig.json`

and don't you think, `noEmit` should be set in tsconfig.json as well? because this is not a typescript project?

**Comment by suneettipirneni** [comment]
> > Ignore my previous comment(s), editing the tsconfig directly will be fine.
> 
> 
> 
> reverted changes to `tsconfig.json`
> 
> 
> 
> and don't you think, `noEmit` should be set in tsconfig.json as well? because this is not a typescript project?

Not at this moment.

**Review by suneettipirneni — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
