### PR TITLE
Feat: Allow fetching Teams

### PR DESCRIPTION
**Pull request by PyroTechniac**
**Please describe the changes this PR makes and why it should be merged:**
This allows fetching of `Teams`

(This also ignore's `.idea` files, which come from WebStorm)

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by appellation** [comment]
I don't believe this change is necessary since teams are only available from the client application and there is no reason to fetch them independently at this point.

**Comment by PyroTechniac** [comment]
While this does have fairly limited use cases, this can be used for scenarios where the `Team` instance is cached (like with most klasa bots, as the `ClientApplication` instance is cached) and needs updating, but the whole Application doesn't, therefore circumventing unnecessary patching

**Comment by appellation** [comment]
There is incredibly negligible benefit to only updating the team rather than the whole application. The most expensive part of the operation is the network call, and there is no way to fetch the team independently from the client application. Thus, the only performance benefit here is some saved object property updates and a new team instance. This is not worth the extra code duplication.

My original concern is still valid: teams do not exist independently of client applications and they should not be treated as such.

**Comment by PyroTechniac** [comment]
Thank you for your input, I understand this feature is negligible.

**Pull request closed without merging**
