### PR TITLE
Options are meant to be optional at least for Client.

### PR DESCRIPTION
**Pull request by LaterIdiot**
**Please describe the changes this PR makes and why it should be merged:**
This PR provides a patch to the typings in which the Client constructor now makes options optional in the typings.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by kyranet** [comment]
They're not optional because if an empty object is passed, the constructor will always throw an error:

https://github.com/discordjs/discord.js/blob/807ea2d3c197c7c6556bd1c894114932f6657d49/src/client/Client.js#L467

This method is called in:

https://github.com/discordjs/discord.js/blob/807ea2d3c197c7c6556bd1c894114932f6657d49/src/client/Client.js#L76

You must always specify `options.intents`, that's an intended breaking change.

**Comment by LaterIdiot** [comment]
> They're not optional because if an empty object is passed, the constructor will always throw an error:
> 
> https://github.com/discordjs/discord.js/blob/807ea2d3c197c7c6556bd1c894114932f6657d49/src/client/Client.js#L467
> 
> This method is called in:
> 
> https://github.com/discordjs/discord.js/blob/807ea2d3c197c7c6556bd1c894114932f6657d49/src/client/Client.js#L76
> 
> You must always specify `options.intents`, that's an intended breaking change.

I meant to say that the argument for 'options' is optional not the options themselves.

**Comment by kyranet** [comment]
`new Client()` without arguments produces this:

image

And if I do this change:

```diff
- const client = new Client();
+ const client = new Client({ intents:['GUILDS'] });
```

Then the bot starts working correctly.

**Comment by LaterIdiot** [comment]
> `new Client()` without arguments produces this:
> 
> image
> 
> And if I do this change:
> 
> ```diff
> - const client = new Client();
> + const client = new Client({ intents:['GUILDS'] });
> ```
> 
> Then the bot starts working correctly.

Yea you are right I made a mistake of not testing after installing discord.js v13 sorry for this PR. I didn't even check the documentation for the master branch which it clearly stated that it's not optional but necessary.

**Pull request closed without merging**
