### PR TITLE
chore: bump dapi-types etc. of djs v13

### PR DESCRIPTION
**Pull request by qyurila**
**Please describe the changes this PR makes and why it should be merged:**

`discord-api-types` had been introducing some breaking changes during 4 minor releases and I encountered one of their side-effect.

<details>
<summary>The error I met (trivial)</summary>

I encountered following TS error while working on my djs v13 bot:

```
Error when loading 'C:\Dev\Personal\yuzubot\src\commands\Basic\ping.ts': src/commands/Basic/ping.ts:49:25 - error TS2379: Argument of type 'APIMessage | Message<boolean>' is not assignable to parameter of type 'Message<boolean> | APIMessage' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
  Type 'APIMessage' is not assignable to type 'Message<boolean> | APIMessage' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
    Type 'import("C:/Dev/Personal/yuzubot/node_modules/.pnpm/discord-api-types@0.33.5/node_modules/discord-api-types/payloads/v9/channel").APIMessage' is not assignable to type 'import("C:/Dev/Personal/yuzubot/node_modules/.pnpm/discord-api-types@0.37.15/node_modules/discord-api-types/payloads/v9/channel").APIMessage' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
```

</details>

This PR also bumps `@discordjs/builders` and `@discordjs/collection` to their v1 releases. (mainly in order to get rid of warnings)

I'm not sure if bumping `@discordjs/collection` from v0.7 to latest has no problem because there was v0.8.  `@discordjs/builders` is OK because its v0.16 was as same as v1.0.

**Status and versioning classification:**

### CODE REVIEW

**Comment by Jiralite** [comment]
Isn't that just a version conflict?

**Comment by kyranet** [comment]
Sadly, I highly doubt we'll pass this because of the https://github.com/discordjs/discord.js/labels/semver%3Amajor nature of this PR.

While yes, there aren't changes on discord.js's code, there are many changes in the underlying packages it depends on, so the API changes in many places unknowingly.

**Comment by qyurila** [comment]
Okay, I got it. Thank you for the kind explanation.
Then, how about adding some advice or modification to v13 guides to specify `discord-api-types` version to ^0.33?
(I'd open an issue if you don't mind and think it would be good.)

**Comment by kyranet** [comment]
For all intents and purposes, we'll always recommend latest version (currently v14) for best stability and access to latest features. v13 is LTS, but there's only so much we can do within semver.

It's also unfortunate that v13 got caught in the middle of many discord-api-types refactors, v14 had the longest -types minor version so far by comparison, so it's able to keep up with the new features, and will be able to do so as long as we don't bump its minor version (which is also why we're avoiding doing breaking changes, and instead just marking them as deprecated).

**Comment by qyurila** [comment]
@kyranet I appreciate your guidance. I'll close this PR and look into that channel!

**Pull request closed without merging**
