### PR TITLE
feat(Message): allow removing attachments

### PR DESCRIPTION
**Pull request by vaporox**
**Please describe the changes this PR makes and why it should be merged:**

This adds support for removing attachments from a message.

**Status and versioning classification:**

- Code changes have been tested against the Discord API
- I know how to update typings and have done so
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Review by CyberFlameGO — APPROVED** [review]

**Review by CyberFlameGO — APPROVED** [review]

**Comment by ThaTiemsz** [comment]
It's also possible to remove a single attachment from messages. This can be done by editing the message with as payload the array of message attachments with the one(s) that you want removed left out.

image

**Comment by monbrey** [comment]
If individual attachments can be edited out, I'm not sure this needs to be a separate `Message#removeAttachments` method/option.

Shouldn't `MessageEditOptions` just have support for an attachments array, in the same way it would embeds?

**Review by vladfrangu — CHANGES_REQUESTED** [review]
What @monbrey said above

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by SpaceEEC — APPROVED** [review]

**Comment by HarmoGlace** [comment]
It was merged although there is no documentation?

**Pull request merged**
