### PR TITLE
perf: use logical assignments instead of if statements

### PR DESCRIPTION
**Pull request by almeidx**
**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by suneettipirneni** [comment]
I'm pretty sure some of these should be using `??=` instead of `&&=`, no?

**Comment by suneettipirneni** [comment]
Disregard that last comment

**Comment by ImRodry** [comment]
Are you sure you covered all instances where this can be applied? I thought there were many more

**Comment by almeidx** [comment]
> Are you sure you covered all instances where this can be applied? I thought there were many more

Probably not. I only used a regex find `if\s*\(!?([\w.]+)\)\s*\{?\s*\1\s*=`

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Comment by iCrawl** [comment]
This needs a rebase.

**Comment by almeidx** [comment]
Rebased

**Review by SpaceEEC — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Pull request merged**
