### PR TITLE
fix(Permissions.FLAGS): `USE_APPLICATION_COMMANDS` -> `USE_SLASH_COMMANDS`

### LINKED ISSUE #6200: Incorrect permission flag for using slash commands
**Please describe the problem you are having in as much detail as possible:**

In the official API Documentation, there is [`USE_SLASH_COMMANDS`](https://discord.com/developers/docs/topics/permissions) permission. However, in djs v13.0 it is listed as [`USE_APPLICATION_COMMANDS`](https://discord.js.org/?source=post_page---------------------------#/docs/main/master/class/Permissions?scrollTo=s-FLAGS). With the library's intention to reflect Discord API as close as possible, that doesn't seem like an intended change.

**Further details:**

- discord.js version: discord.js@13.0.0-dev.30a58dc.1627430624
- Node.js version: v16.4.0
- Operating system: *n/a*
- Priority this issue should have – please be realistic and elaborate if possible: *low*

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

### PR DESCRIPTION
**Pull request by vBread**
**Please describe the changes this PR makes and why it should be merged:**
Fixes #6200 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by iCrawl** [comment]
I'd be careful here, this might with the current iteration of context menus heavily clash with them.

They are application commands and still share the same permission.

**Comment by vBread** [comment]
I'll keep this open for now and close if there's a PR to the DAPI docs once context menus release to change the permission name.

**Review by KifoPL — APPROVED** [review]
LGTM

**Comment by KifoPL** [comment]
> I'd be careful here; With the current iteration of context menus this might heavily clash with them.
> 
> They are application commands and still share the same permission.

@iCrawl true, but with that in mind I think Discord will either prepare more permissions, or clear things up - for now, it's officially `USE_SLASH_COMMANDS`, and that's how it should be shipped  ¯\_(ツ)_/¯

**Comment by advaith1** [comment]
the permission is actually `USE_APPLICATION_COMMANDS` internally but was documented as `USE_SLASH_COMMANDS`, it might be changed in the docs though

I strongly support leaving it as `USE_APPLICATION_COMMANDS` in d.js

**Review by Dreamedc2015 — APPROVED** [review]

**Comment by GoldenAngel2** [comment]
`USE_SLASH_COMMANDS` is being renamed to `USE_APPLICATION_COMMANDS` in the discord api docs

PR: https://github.com/discord/discord-api-docs/pull/3614

**Comment by vBread** [comment]
Closing 👍🏼

**Pull request closed without merging**
