### PR TITLE
Update index.d.ts - Addition to Channel class

### PR DESCRIPTION
**Pull request by jackcaldwell92**
Send function added to channel class in typescript typings. Function seems to take a string and return a promise that should resolve to a Message. I'm presuming there are options to provide other argument types for sending files etc, but this was an issue that I encountered fairly early on in my usage of the library. Let me know if I'm missing something / your thoughts on this PR generally. 
Thanks for an awesome library.

**Please describe the changes this PR makes and why it should be merged:**

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by vladfrangu** [comment]
This is invalid, as Channel is just a base that all other types of channel extend (see, Voice, Category, Text, DM). The channels that can send a message have the function defined

**Comment by jackcaldwell92** [comment]
Thanks for your quick response. I'm just wondering if you have any ideas of how else I may be able to fix the issue of 'Property 'send' does not exist on type 'Channel'' when trying to call this method on an instance of Channel?

**Comment by tipakA** [comment]
Most likely because it wasn't a text channel. You can't send to voice or category, and they're channels as well

**Comment by Dev-Yukine** [comment]
You should only call this on TextChannel or make sure that you cast channels with type "text" to one before trying to send messages.

**Comment by jackcaldwell92** [comment]
Ok, I think I understand. Thanks, everyone

**Pull request closed without merging**
