### PR TITLE
Move createReactionCollector to ReactionStore

### PR DESCRIPTION
**Pull request by jpbberry**
**Please describe the changes this PR makes and why it should be merged:**
Going along with the `master` store changes. Also moved awaitReactions.

**Status**
- [X] Code changes have been tested against the Discord API, or there are no code changes
- [X] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [X] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Monbrey** [comment]
Not sure I agree, this feels like change for the sake of change.

The DataStores, as the name suggests, store data. They're containers, like the Collections/Maps+Arrays they're based on.

I don't feel these methods belong in the store. When you're waiting for reactions (or messages), even though programmatically they end up in the store, you're waiting for Reactions on a Message. Waiting for Messages in a TextChannel. It makes sense for those methods to be attached to the instances of Message/TextChannel respectively.

On the other hand, I almost think the createCollector methods could be done away with completely if stores had events of their own, example:
`message.reactions.on('reactionAdd', (reaction, user) => { ... })`

**Comment by jpbberry** [comment]
> though programmatically they end up in the store, you're waiting for Reactions on a Message.
I see where you're coming from but it also kinda makes sense that you're collection reactions from the collection itself. I'm kinda stuck in the middle as well but right now it kinda sounds logical to do it like this. The more I think about it it keeps switching back and forth :p

**Comment by Monbrey** [comment]
> Edit: or almost that it seems redundant to have create**Reaction**Collector

Redundant naming if moved, yes, but I don't think moving a function for the sake of naming it is important

**Comment by appellation** [comment]
The only way I could see this being a good design decision is if collectors get abstracted into collections directly rather than being event-based as they are currently: for example, `Collection#collect(filter, options): Collector`. In this scenario, collectors would work directly off of insertions/deletions on the collection itself rather than based on event emissions. That being said, I don't think implementing this is worthwhile: the existing system works quite well with event-based collection and this would involve a complete rewrite of our collector system. You're welcome to take a stab at it if you feel so inclined.

**Comment by jpbberry** [comment]
I don’t think a rewrite is necessary for that, while it does sound interesting but, no. The thing I’m trying to take out of this is the actual creation of it, moving it out of the way of the message object and moving it to the prop that has almost everything to do with it.

**Comment by appellation** [comment]
@Monbrey hit the nail on the head when he said that data stores are a data container. The current collector implementation has absolutely nothing to do with data containment, which is why they have been implemented as convenience methods on the objects that they are designed to collect. Since collectors are event based, technically they should be implemented with methods on structures that are `EventEmitter`s; since all of our events are emitted on the client, we do the next best thing with implementing the convenience methods on the structures that the event is happening on (i.e. the structures the event *would* be emitted on if they were event emitters).

If you want to add collectors to data stores, I wouldn't hate it. However, this is not a generic implementation to do so; your PR just moves some stuff around for the stated purpose of moving a term in the method name:

>it seems redundant to have create**Reaction**Collector, rather than just append it to the already made reactions prop

Short of the poor design choices in this PR, I hope you can at least agree that it's objectively incorrect to do this with only one of the two collectors we built into the library. Making this a generic implementation as I described above would address this issue, but at the very least this should be done manually for all the implementations in the library.

**Pull request closed without merging**
