### PR TITLE
types: fix MessageMentions channel types

### PR DESCRIPTION
**Pull request by oof2win2**
**Please describe the changes this PR makes and why it should be merged:**

Fixed typings to allow for other channel types other than TextBasedChannel in MessageMentions.channels, such as voice. Also removed DMChannels from those types, as you cannot mention a DMChannel - the ID of a DMChannel is the user's ID, which is only valid under a user mention.

**Status and versioning classification:** Patch

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by imranbarbhuiya** [comment]
You can mention a dm channel. Also dm channels I'd isn't same as user ID.

**Comment by oof2win2** [comment]
Taking the ID from the URL and pasting it as a usual channel mention doesn't work, it only sends the name of the DM recipient.
Screenshot 2022-01-21 at 17 37 33
Screenshot 2022-01-21 at 17 39 21

**Comment by Jiralite** [comment]
It doesn't matter what happens in your client - `DMChannel`s can be parsed if you use the channel's id. If you look at our implementation:

https://github.com/discordjs/discord.js/blob/c10afeadc702ab98bec5e077b3b92494a9596f9c/packages/discord.js/src/structures/MessageMentions.js#L157-L166

You can see that we match via a regular expression here. So yes, a `DMChannel` can be matched here but also any other kind of channel - `StageChannel`... `StoreChannel`... so the typings here still aren't correct, however.

**Comment by Jiralite** [comment]
The opposite actually: the JavaScript isn't the issue, the typings are.

**Comment by oof2win2** [comment]
Should DMChannels still be excluded? IMO they should since you shouldn't be able to mention them, but it's a channel type.

**Comment by Syjalo** [comment]
> Should DMChannels still be excluded? IMO they should since you shouldn't be able to mention them, but it's a channel type.

It's shouldn't be excluded. You able to mention it, but the desktop version of Discord don't resolves it. In mobile version of Discord the DMChannel mentions works fine. Also discord.js includes the mention to the channels collection.

**Comment by oof2win2** [comment]
I see. The current code in this PR allows for any channel to be mentioned.

**Review by SpaceEEC — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Pull request merged**
