### PR TITLE
docs(interaction): add locale list link

### PR DESCRIPTION
**Pull request by ImRodry**
**Please describe the changes this PR makes and why it should be merged:**

This PR adds a link to a list of all possible locales from Discord's documentation to Interaction#locale

**Status and versioning classification:**
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by suneettipirneni** [comment]
Could you also add a `LocaleString` type that's a union of all the locale types?

**Comment by ImRodry** [comment]
I don’t know how often Discord adds locales but should we be the ones documenting that? I mean if they do add some the code doesn’t need to be updated but we’d need to update that typedef whereas a simple link to the API docs is always up to date

**Comment by DTrombett** [comment]
> Could you also add a LocaleString type that's a union of all the locale types?

Maybe this can be done in `discord-api-types`?
I think it would be good to have an enum/type of the possible locale codes

**Review by iCrawl — APPROVED** [review]

**Comment by almeidx** [comment]
`LocaleString` could be used instead of `string` when/if this is released
- https://github.com/discordjs/discord-api-types/pull/297

**Comment by ImRodry** [comment]
There's no point if it's not gonna link to anything anyways right

**Comment by almeidx** [comment]
I meant the TS type of it, but that may be done on a separate pull request I suppose

**Comment by advaith1** [comment]
uh... I just moved this yesterday

**Comment by ImRodry** [comment]
Well it still works so will update when it stops doing so

**Review by CryptoGodfatherVA2 — APPROVED** [review]

**Comment by Th1983** [comment]
thank

**Pull request merged**
