### PR TITLE
Added a spoiler message option

### PR DESCRIPTION
**Pull request by S0ftwareUpd8**
**Please describe the changes this PR makes and why it should be merged:**

This pull request adds a spoiler option which can be passed into the message options. 

**Status**
- [x] Code changes have been tested against the Discord API, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
- [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Monbrey** [comment]
mfw 209 changed files

**Comment by didinele** [comment]
209 changed files :meguFace:

**Comment by Darqam** [comment]
I'm not sure why one would want this. It's not a part of the api, and it's longer to do `...send('stuff', {spoiler:true})` rather than just `...send('||stuff||')`. Plus what happens if someone wants to send only a portion of it marked as spoiler?

**Comment by S0ftwareUpd8** [comment]
OK somehow I changed 209 files so I'm gonna close this and reopen this when I actually figure out how to use git

**Pull request closed without merging**
